### ISSUE TITLE
Change tab list config structure

### ISSUE THREAD

**Issue by CodeCrafter47** [CodeCrafter47/BungeeTabListPlus#113]
I've been thinking about how the configuration of the plugin can be improved in order to be more simple and more powerful.

This is not yet implemented in the plugin. Any feedback and ideas are welcome. I hope to make the configuration of this plugin as simple as possible.

Why
---

The way the configuration files of the plugin are structured currently is difficult to understand and can be confusing to server admins.

In addition to the config files being easier to understand this change will allow for more flexible designs.

Goals
-----
 * Make the configuration of the plugin easier to understand.
 * Creating an extendable config system so that new features can be added without problems.
 * Adding many new features: e.g. allow every slot to be animated, finer control over players shown in the tab list, ...

Examples
--------

Example how the default config looks in the new format. This is just a basic so you get a feeling for the new config structure.
```yaml
showTo: "true"
priority: 10

type: FIXED_SIZE

showHeaderFooter: false

defaultIcon: colors/dark_gray.png
defaultPing: 1000
size: 60
playerSets:
  global:
    filter: "true"
components:
- {text: "&cServer: &6${viewer server}", icon: "default/server.png", ping: 0}
- {text: "&cRank: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
- {text: "&cPing: &6${viewer ping}ms", icon: "default/ping.png", ping: 0}
- !players_by_server
  playerSet: global
  serverHeader:
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  includeEmptyServers: true
  playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
  minSize: 48
  maxSize: 48
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "&6=============", icon: "colors/gold.png", ping: 0}
- {text: "&6=============", icon: "colors/gold.png", ping: 0}
- {text: "&6=============", icon: "colors/gold.png", ping: 0}
- {text: "&cTime: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
- {text: "&cPlayers: &6${playerset:global size}", icon: "default/players.png", ping: 0}
- {text: "&cBalance: &6${viewer vault_balance}", icon: "default/balance.png", ping: 0}
```
![](http://pictures.codecrafter47.dyndns.eu/pictures/2016-07-15_10.20.26.png)

A more advanced example:
```yaml
showTo: '${viewer name} == "CodeCrafter47"'
priority: 15

type: FIXED_SIZE

showHeaderFooter: false

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000
size: 80

playerSets:
  global:
    filter: "true"
  lobby:
    filter: |-
      ${player server} == "lobby"
  survival:
    filter: |-
      ${player server} == "survival"
  creative:
    filter: |-
      ${player server} == "creative"

components:
- !table
  columns:
    0:
    - {text: "&lInfo", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cServer:", icon: "default/server.png", ping: 0}
    - {text: "&6${viewer server}", icon: "default/server.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cRank:", icon: "default/rank.png", ping: 0}
    - {text: "&6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPing:", icon: "default/ping.png", ping: 0}
    - {text: "&6${viewer ping}ms", icon: "default/ping.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPlayers:", icon: "default/players.png", ping: 0}
    - {text: "&6${playerset:global size}", icon: "default/players.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cBalance:", icon: "default/balance.png", ping: 0}
    - {text: "&6${viewer vault_balance}", icon: "default/balance.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cTime:", icon: "default/clock.png", ping: 0}
    - {text: "&6${time HH:mm:ss}", icon: "default/clock.png", ping: 0}
    1-2:
    - {text: "&a&lLobby", icon: "colors/green.png", ping: 0}
    - {text: "&a&lLobby", icon: "colors/green.png", ping: 0}
    - !players
      playerSet: lobby
      playerComponent: {text: "${player vault_prefix}${player name}", icon: "${player skin}", ping: "${player ping}"}
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    3:
    - {text: "&b&lSurvival", icon: "colors/aqua.png", ping: 0}
    - !players
      playerSet: survival
      playerComponent: {text: "${player vault_prefix}${player name}", icon: "${player skin}", ping: "${player ping}"}
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
      minSize: 9
      maxSize: 9
    - {text: "&c&lCreative", icon: "colors/red.png", ping: 0}
    - !players
      playerSet: creative
      playerComponent: {text: "${player vault_prefix}&f${player name}", icon: "${player skin}", ping: "${player ping}"}
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
      minSize: 9
      maxSize: 9
```
![](http://pictures.codecrafter47.dyndns.eu/pictures/2016-07-15_10.59.43.png)

Explanation
-----------

This is the basic structure of the tab list config:
```yaml
showTo: "all"
priority: 0
type: FIXED_SIZE # used to detect the new config format

showHeaderFooter: false # if true add the same four entries as in the old config format

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000
size: 80

playerSets: <Player sets>

components: <List of components>
```

The interesting thing is the `components` entry as it replaces several of the previous config options. For info on how player sets work see my comment below.

The following components are available:

1. **Basic Component**

   ```yaml
   {text: "...", icon: "image.png", ping: 0}
   ```

   Should be self-explaining.
2. **Animated Component**

   ```yaml
   !animated
   components: <List of Compopnents>
   interval: <Number>
   ```
   Example:
   ```yaml
   !animated
   components:
     - {text: "&7Hello &a${player name}", icon: "${player skin}", ping: 0}
     - {text: "&7Hello &b${player name}", icon: "${player skin}", ping: 0}
     - {text: "&7Hello &c${player name}", icon: "${player skin}", ping: 0}
     - {text: "&7Hello &d${player name}", icon: "${player skin}", ping: 0}
   interval: 0.4
   ```
   With this component it will finally be possible to animate every single slot
    of the tab list.

   | Option | Description |
   | ------ | ----------- |
   | `components` | These components will be cycled through. |
   | `interval` | Interval in seconds at which to switch the active Component. |

3. **Conditional Component**

   ```yaml
   !conditional
   condition: <Expression>
   true: <Replacement if the condition evaluates to true>
   false: <Replacement if the condition evaluates to false>
   ```
   Example:
   ```yaml
   !conditional
   condition: |-
     ${server:survival online} == true
   true: {text: "&bSurvival: &aONLINE", icon: "colors/green.png", ping: 0}
   false: {text: "&bSurvival: &cOFFLINE", icon: "colors/red.png", ping: 0}
   ```
   This component can dynamically change the content of the tab list. The example shows how this could replace the {onlineState} variable.

   | Option | Description |
   | ------ | ----------- |
   | `condition` | The expression to be evaluated. |
   | `true` | Replacement if the condition evaluates to true. |
   | `false` | Replacement if the condition evaluates to false. |

4. **Players Component**

   ```yaml
   !players
   playerSet: <String>
   playerOrder: <String>
   playerComponent: <Component or list of components>
   morePlayersComponent: <Component or list of components>
   minSize: <Number>
   maxSize: <Number>
   ```
   Example:
   ```yaml
   !players
   playerSet: global
   playerOrder: "adminFirst,alphabetically"
   playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
   morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
   minSize: 0
   maxSize: 6
   ```
   This component provides a simple way of adding players to the tab list.

   | Option | Description |
   | ------ | ----------- |
   | `playerSet` | Selects which players will be added to the tab list. |
   | `playerOrder` | Works like the [SORT=...] in the old config format.
   | `playerComponent` | Determines how a player will be presented in the tab list. Usually you will want to set this to `{text: "${player name}", icon: "${player skin}", ping: "${player ping}"}`, eventually adding a prefix. This can be set to a list of basic components to use more than one slot per player. |
   | `morePlayersComponent` | This will be shown if there are more players than there is space in the tab list (or more players than `max-size`) |
   | `minSize` | Optional: Minimum slots this component should use |
   | `maxSize` | Optional: Maximum slots this component should use |

5. **Players by Server Component**

   ```yaml
   !players_by_server
   playerSet: <String>
   playerOrder: <String>
   serverHeader: <List of Components>
   includeEmptyServers: <Boolean>
   playerComponent: <Component or list of components>
   morePlayersComponent: <Component or list of components>
   minSizePerServer: <Number>
   maxSizePerServer: <Number>
   minSize: <Number>
   maxSize: <Number>
   ```
   Example:
   ```yaml
   !players_by_server
   playerSet: global
   playerOrder: "adminFirst,alphabetically"
   serverHeader:
   - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
   includeEmptyServers: false
   playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
   morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
   minSizePerServer: 3
   maxSizePerServer: 18
   minSize: 6
   maxSize: 48
   ```
   This component adds players to the tab list grouping them by server like seen in the default config.

   | Option | Description |
   | ------ | ----------- |
   | `playerSet` | Selects which players will be added to the tab list. |
   | `playerOrder` | Works like the [SORT=...] in the old config format.
   | `serverHeader` | This component groups players by the server they are connected to. The server header will appear once for each server above the players playing on that server. |
   | `includeEmptyServers` | Whether empty servers will show up too. |
   | `playerComponent` | Determines how a player will be presented in the tab list. Usually you will want to set this to `{text: "${player name}", icon: "${player skin}", ping: "${player ping}"}`, eventually adding a prefix. This can be set to a list of basic components to use more than one slot per player. |
   | `morePlayersComponent` | This will be shown if there are more players than there is space in the tab list (or more players than `max-size`) |
   | `minSizePerServer` | Optional: Minimum slots to use for a single server |
   | `maxSizePerServer` | Optional: Maximum slots to use for a single server |
   | `minSize` | Optional: Minimum slots this component should use |
   | `maxSize` | Optional: Maximum slots this component should use |

6. **Table**

   ```yaml
   !table
   columns:
   <Column number(s)>: <List of Components>
   ```
   Example:
   ```yaml
   !table
   columns:
     0-1:
       - {text: "Survival"}
       - {text: ""}
       - !players
         playerSet: survival
         playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
         morePlayersComponent: {text: "... and ${other_count} others", skin: "default/players.png", ping: 0}
     2:
       - {text: "Stats:"}
       - {text: "Playtime:"}
       - {text: "  Total: ${viewer bungeeonlinetime}"} # just an example, these placeholders don't exist (yet)
       - {text: "  Session: ${viewer onlinetime}"}
       - {text: ""}
       - {text: "Balance: ${viewer vault_balance}"}
       - {text: ""}
       - {text: "Faction: ${viewer faction}"}
   ```
   Allows setting the content for the columns independently. This is intended to be a more powerful replacement for the `verticalMode` option.

**Comment by kaenganxt** [comment]
The syntax looks really good to me, but I additionally have some ideas:
- Config version: I think you should keep support for the old version if server owners don't want to change their working config files, so you could maybe add a version:2 flag or detect the syntax type automatically
- Custom filters/conditions: A way for another plugin to register custom placeholders, which work like the current PlayerManager.Filter class, so server owners can create extremly customized tablists without generating them completely through a plugin

**Comment by CodeCrafter47** [comment]
So I've been thinking about how to improve this further, and created a first (not yet public) implementation of the system to see how it works out.

Besides some renames of the config entries (e.g. I changed `skin` to `icon`) I came up with the following bigger ideas.

Detecting config version
------------------------

To detect whether the config uses the new format I added a type field:
```yaml
type: FIXED_SIZE
```
Configuration files using the old format don't have that one.

The idea behind the type field is that there will also be another type which is more close to the vanilla tab list, i.e. one slot per player, no custom slots, size of the tab list adjusts to the amount of players online.

Placeholders
------------

I thought it would be nice to be able to use the same placeholders for the filters and conditions as are used in the regular text.

The proposed change will only affect configs using the new format.

So I came up with the following idea: Each player related placeholder comes in two versions: One for the player viewing the tab list on one for a player displayed in the tab list. E.g. instead of `{name}` there will be `${viewer name}` and `${player name}`. The first one can be used everywhere, the second one in player slots and filters.

Some examples:

Old placeholder | New "viewer" placeholder | New "player" version
--------------- | ------------------------ | --------------------
`{name}` | `${viewer name}` | `${player name}`
`{server}` | `${viewer server}` | `${player server}`
`{faction}` | `${viewer faction}` | `${player faction}`
`{vault_prefix}` | `${viewer vault_prefix}` | `${player vault_prefix}`

That would make it very easy to create filters which match all players on the same server or in the same faction.

Filter that matches all players on the same server:
```yaml
filter: |-
  ${player server} == ${viewer server}
```

Filter that matches all players in the same faction:
```yaml
filter: |-
  ${player server} == ${viewer server} && ${player faction} == ${viewer faction}
```

That change would also impose some changes to the non player related placeholders, so everything still looks nice:

Old placeholder | Suggested replacement
--------------- | ---------------------
`{tps}` | `${viewer server tps}` <br/>A server related placeholder can be resolved for the server the player viewing the tab list is on.
`{tps:lobby}` | `${server:lobby tps}`<br/>Or for a specific server.
`{time}` | `${time HH:mm:ss}` <br/>The changed time placeholder allows specifying the format directly.
`{other_count}` | `${other_count}`<br/>The `{other_count}` special placeholder barely changes
`{server_player_count}` | `${server_player_count}`<br/>Another special placeholder for use in the serverHeader of the players by server component.

Not 100% sure how placeholders from PlaceholderAPI will work after this change but I think the easiest solution would be that `%statistic_mine_block%` will be replaced with `${player statistic_mine_block}` and the viewer equivalent.

This is just a rough insight in how I imagine it to work, please have a look at the config examples above and below to see how it looks in action.

Player sets
-----------

Having the filters allowing to select which players to display more precisely the before brought up another problem: How to make that work together with the player count placeholders.

To solve this problem I added the `playerSets` entry to the config. It contains the filters and gives them names. Example how it can look:

```yaml
playerSets:
  global:
    filter: "true"
  lobby:
    filter: |-
      ${player server} == "lobby"
  survival:
    filter: |-
      ${player server} == "survival"
  creative:
    filter: |-
      ${player server} == "creative"
```

Instead of containing a filter the player components now contain a reference to a player set:

```yaml
!players
playerSet: lobby
playerComponent: {text: "${player vault_prefix}${player name}", icon: "${player skin}", ping: "${player ping}"}
morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
```

And to insert the player count for a player set the `${playerset:lobby}` placeholder can be used.

Eventually I will add an additonal option to the player sets so it can be specified whether or not they should include hidden players.

Some examples
-------------

Here are some more examples:

An improved variation of the default config showing animations in action:
```yaml
showTo: "true"

priority: 20

type: FIXED_SIZE

showHeaderFooter: true

header:
  - |-
    &6Hello ${viewer name}
    &eLine 2
  - |-
    &eHello ${viewer name}
    &6Line 2

headerAnimationUpdateInterval: 0.5

footer:
  - |-
    &6Line 1
    &eLine 2
  - |-
    &eLine 1
    &6Line 2

footerAnimationUpdateInterval: 0.5

defaultIcon: colors/dark_gray.png
defaultPing: 1000
size: 60
playerSets:
  global:
    filter: "true"
components:
- {text: "&cServer: &6${viewer server}", icon: "default/server.png", ping: 0}
- {text: "&cRank: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
# Show ping in different colors depending on how good/ bad it is
- !conditional
  condition: |-
    ${viewer ping} < 50
  true: {text: "&cPing: &a${viewer ping}ms", icon: "default/ping.png", ping: 0}
  false: !conditional
    condition: |-
      ${viewer ping} < 150
    true: {text: "&cPing: &e${viewer ping}ms", icon: "default/ping.png", ping: 0}
    false: {text: "&cPing: &c${viewer ping}ms", icon: "default/ping.png", ping: 0}
- !players_by_server
  playerSet: global
  serverHeader:
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  includeEmptyServers: true
  playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
  minSize: 48
  maxSize: 48
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
# Nice animations at the bottom
- !animated
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- !animated
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- !animated
  interval: 0.2
  components:
  - {text: "&6&c=&6==============", icon: "colors/gold.png", ping: 0}
  - {text: "&6=&c=&6=============", icon: "colors/gold.png", ping: 0}
  - {text: "&6==&c=&6============", icon: "colors/gold.png", ping: 0}
  - {text: "&6===&c=&6===========", icon: "colors/gold.png", ping: 0}
  - {text: "&6====&c=&6==========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=====&c=&6=========", icon: "colors/gold.png", ping: 0}
  - {text: "&6======&c=&6========", icon: "colors/gold.png", ping: 0}
  - {text: "&6=======&c=&6=======", icon: "colors/gold.png", ping: 0}
  - {text: "&6========&c=&6======", icon: "colors/gold.png", ping: 0}
  - {text: "&6=========&c=&6=====", icon: "colors/gold.png", ping: 0}
  - {text: "&6==========&c=&6====", icon: "colors/gold.png", ping: 0}
  - {text: "&6===========&c=&6===", icon: "colors/gold.png", ping: 0}
  - {text: "&6============&c=&6==", icon: "colors/gold.png", ping: 0}
  - {text: "&6=============&c=&6=", icon: "colors/gold.png", ping: 0}
  - {text: "&6==============&c=&6", icon: "colors/gold.png", ping: 0}
- {text: "&cTime: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
- {text: "&cPlayers: &6${playerset:global size}", icon: "default/players.png", ping: 0}
- {text: "&cBalance: &6${viewer vault_balance}", icon: "default/balance.png", ping: 0}
```
![](http://pictures.codecrafter47.dyndns.eu/pictures/anim2.gif)

Something with factions (#97):

```yaml
showTo: '${viewer server} == "factions"'
priority: 25

type: FIXED_SIZE

showHeaderFooter: false

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000
size: 60

playerSets:
  global:
    filter: "true"
  faction:
    filter: |-
      ${player faction} == ${viewer faction}

components:
- !table
  columns:
    0:
    - {text: "&lInfo", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cServer:", icon: "default/server.png", ping: 0}
    - {text: "&6${viewer server}", icon: "default/server.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cRank:", icon: "default/rank.png", ping: 0}
    - {text: "&6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPing:", icon: "default/ping.png", ping: 0}
    - {text: "&6${viewer ping}ms", icon: "default/ping.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPlayers:", icon: "default/players.png", ping: 0}
    - {text: "&6${playerset:global size}", icon: "default/players.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cBalance:", icon: "default/balance.png", ping: 0}
    - {text: "&6${viewer vault_balance}", icon: "default/balance.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cTime:", icon: "default/clock.png", ping: 0}
    - {text: "&6${time HH:mm:ss}", icon: "default/clock.png", ping: 0}
    1:
    - {text: "&a&lPlayers", icon: "colors/green.png", ping: 0}
    - !players
      playerSet: global
      playerComponent: {text: "${player vault_prefix}&f${player name}", icon: "${player skin}", ping: "${player ping}"}
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    2:
    - !conditional
      condition: |-
        ${viewer faction} == ""
      true:
      - {text: "&6Faction list", icon: "colors/gold.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "Not in a Faction", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "   Join one!", icon: "colors/dark_gray.png", ping: 1000}
      false:
      - {text: "&6Faction &f${viewer faction}", icon: "colors/gold.png", ping: 1000}
      - {text: "${playerset:faction size} &6Players online", icon: "colors/gold.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - !players
        playerSet: faction
        playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
```
![](http://pictures.codecrafter47.dyndns.eu/pictures/anim3.gif)
