### ISSUE TITLE
Help for recovery of variable number of players

### ISSUE THREAD

**Issue by NyCoSD** [CodeCrafter47/BungeeTabListPlus#124]
Hello,
Could you tell me the variable to use for the number of connected recovered from a special server?
As in the old version : **{player :"SERVER"}** (For example)
Thank you in advance.

**Comment by CodeCrafter47** [comment]
You need to create a player set that contains all players on that server. Example:
```yaml
playerSets:
  ...
  lobby:
    filter: |-
      ${player server} == "lobby"
```
Then you can use the `${playerset:lobby size}` placeholder.
