### ISSUE TITLE
Sorting rule "vaultGroupInfo" does not exists

### ISSUE THREAD

**Issue by Mrtenz** [CodeCrafter47/BungeeTabListPlus#126]
I'm trying to use "vaultGroupInfo" as sorting rule, however this shows up in the console:
[WARNING] [BungeeTabListPlus] Sorting rule "vaultGroupInfo" does not exists.

My config looks like this:
```
- !players_by_server
  playerSet: global
  playerOrder: "vaultGroupInfo,alphabetically"
  serverHeader:
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  includeEmptyServers: true
  playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
```

I am using version 2.6.1.
