### ISSUE TITLE
Entering spectate gamemode places your player head on the last line of the tab list.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#143]
PaperSpigot dev 883 (Spigot 1.10.2)
Waterfall (BungeeCord) dev 59
BungeeTabListPlus dev 661 (BukkitBridge & Bungee version)

Config.
http://paste.ubuntu.com/23282043/

TabList
http://paste.ubuntu.com/23282049/

```
# whether to show players in spectator mode
# This option will be removed soon. Don't use it anymore.
showPlayersInGamemode3: true
```

Players who are in the spectate gamemode have their head icon replacing the very last slot in the tab list.
![link](http://i.imgur.com/Kl48IN9.png)

Tested with showPlayersInGamemode3 both true and false - occurs in both cases. Exiting spectate mode, the ping image icon reappears. 

As well as player name is not italicized when in the spectate gamemode similar to just a local server vanilla tab list with Essentials installed?

**Comment by CodeCrafter47** [comment]
This happens due to client limitations and can't be fixed.

If the players icon appearing on the last slot of the tab list when in spectator mode is a huge back-draw to you, you can use one of the following tricks to prevent it from happening:

1. Configure the tab list to have a size of 80 slots.
2. Or configure the BungeeTabListPlus tab list to not be shown to players in spectator mode: `showTo: "${viewer gamemode} != 3"`

You can use a custom placeholder to modify the format of player names of spectators:
```yaml
customPlaceholders:
  # ...
  spectator_mode_prefix:
    !conditional
    condition: '${player gamemode} == 3'
    true: '&7&o' # spectator mode
    false: '' # some other game mode

# ...
  playerComponent: "${player vault_prefix}${spectator_mode_prefix}${player display_name}${afk_tag}"
```
