### ISSUE TITLE
ASkyBlock & Spigot Friend's Support

### ISSUE THREAD

**Issue by Zendrex** [CodeCrafter47/BungeeTabListPlus#162]
Hey, so due to either MVDW placeholder or placeholder api having support for either of these plugins I was wondering if you could add support for them like you have with factions. I know there are many other features that you want to add first, but if you get the time, this would be greatly appreciated. What i'm looking for are arrays like you do for faction members, but for askyblock team members, and friend online from spigot friends.

ex of my config.
```
    0-1:
      - {text: "&3&lPlayers Online&8 - &f${playerset:Global size}", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      - !players
        playerSet: SkyBlock
        playerComponent: {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7&o... and ${other_count} more&r", icon: "default/players.png", ping: 0}
        minSize: 38
        maxSize: 38
```

The only thing I cant figure out currently (maybe because its 2:30 in the morning) is how it would ONLY list players in rows 0 and 1 if they are not in the same skyblock team as yourself (due to the fact that they would be on row 3 in the same manner that row 0-1 is set up). This would be the same thing for friends. If anything that I am saying doesn't make sense, I will try to clear it up when I awake.

ASkyBlock API - 

> mvdw has partial support however its broken and he has yet to fix it after 2 months of requesting a fix.

http://tastybento.github.io/askyblock/

Spigot Friends API
https://www.spigotmc.org/resources/spigot-friend-api-for-party-and-friends-for-bungeecord.12597/
