### ISSUE TITLE
Comparison with float (TPS)

### ISSUE THREAD

**Issue by lululombard** [CodeCrafter47/BungeeTabListPlus#174]
Hi there !
I was trying to make a custom placeholder for my server state, but it's not working :
```yml

  lobby_colored_tps0:
    !conditional
    condition: "${server:lobby tps} < 18"
    true: '&e${server:lobby tps}'
    false: '&a${server:lobby tps}'
  lobby_colored_tps1:
    !conditional
    condition: "${server:lobby tps} < 15"
    true: '&6${server:lobby tps}'
    false: '${lobby_colored_tps0}'
  lobby_colored_tps:
    !conditional
    condition: "${server:lobby tps} < 10"
    true: '&c${server:lobby tps}'
    false: '${lobby_colored_tps1}'
  lobby_state_color:
    !conditional
    condition: ${server:lobby online}
    true: '${lobby_colored_tps}'
    false: '&a&lOFF'
```
The issue is that "lobby_colored_tps" always returns true even if ${server:lobby tps} is above 10.
