### ISSUE TITLE
Possible grouping issue (sponge / vault (luckperms))

### ISSUE THREAD

**Issue by Huene** [CodeCrafter47/BungeeTabListPlus#175]
Can someone confirm that the correct groups are being displayed, I've doublechecked my permissions (using luckperms) and showing vault_primary_group shows as "mod" which is fine in that it's pulling it, but my primary is "admin" 

Relevant information follows

tabLists/default.yml
```
customPlaceholders:
  custom_prefix:
    !switch
    expression: ${player vault_primary_group}
    replacements:
      "admin": "&f[&6A&f]&f "
      "mod": "&f[&eM&f]&f "
      "vip": "&f[&aV&f]&f "
```

tabLists/default.yml
```
  playerComponent:
    - {text: "${custom_prefix}&f${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}

```

![image](https://cloud.githubusercontent.com/assets/1078934/21993859/e977f90a-dbea-11e6-8410-77bc1ebc004a.png)

![image](https://cloud.githubusercontent.com/assets/1078934/21993903/27a9be34-dbeb-11e6-9f43-0f1972ead8f0.png)
