### ISSUE TITLE
Question how to color names by rank.

### ISSUE THREAD

**Issue by Zilacon** [CodeCrafter47/BungeeTabListPlus#181]
So if i do ${player vault_prefix} it shows the rank tag and bleeds player names out of the tablist.
Is there a way i can define colors to player names based on what rank they are?

**Comment by CodeCrafter47** [comment]
One possibility is to use `${player vault_prefix 2}` to display just the first two characters of the prefix. Assuming these are a color code it does what you want.

Another option is to use the custom placeholder mechanism to configure the tablist prefixes independent from the permission prefixes. To do that add the following code to config.yml:
```yaml
customPlaceholders:
  # ...
  custom_prefix:
    !switch
    parameters: 1
    expression: ${%0 vault_primary_group}
    replacements:
      "admin": "&c[A]&f"
      "mod": "&b[M]&f"
      "vip": "&b[V]&f"
    defaultReplacement: "&7"
``` 
Edit the lines after `replacements` to configure the prefixes. Then use `${custom_prefix player}` to display the custom prefix.
