### ISSUE TITLE
Need help with tablist

### ISSUE THREAD

**Issue by GijssiexD** [CodeCrafter47/BungeeTabListPlus#198]
Hello,

Im not very experienced in programming and such and I challanged myself by making a tablist for  BungeeTabListPlus.

```
showTo: "all"
priority: 22

showHeaderFooter: true

header:
- '&3Welcome &7${viewer name}'
- '&7W&3elcome &7${viewer name}'
- '&7We&3lcome &7${viewer name}'
- '&7Wel&3come &7${viewer name}'
- '&7Welc&3ome &7${viewer name}'
- '&7Welco&3me &7${viewer name}'
- '&7Welcom&3e &7${viewer name}'
- '&7Welcome &7${viewer name}'
- '&3W&7elcome &7${viewer name}'
- '&3We&7lcome &7${viewer name}'
- '&3Wel&7come &7${viewer name}'
- '&3Welc&7ome &7${viewer name}'
- '&3Welco&7me &7${viewer name}'
- '&3Welcom&7e &7${viewer name}'
- '&3Welcome &7${viewer name}'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &7SurviviaNetwork
  &3http://survivianetwork.buycraft.net
- |-
  &3SurviviaNetwork
  &7http://survivianetwork.buycraft.net

footerAnimationUpdateInterval: 0.5

customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: ' &3AFK'
    false: ''
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

playerSets:
  global:
    filter: "true"
  hub:
    filter: ${player server} == "hub"
  survival:
    filter: ${player server} == "survival"
  kitpvp:
    filter: ${player server} == "kitpvp"

type: FIXED_SIZE	
size: 60	
	
defaultIcon: colors/dark_gray.png
defaultPing: 1000

	
components:
- !table
  columns:
    0:
      - {text: "&7Server: &2${viewer server}", icon: "colors/dark_gray.png", ping: 0}
	  - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
	  - {text: "&3Hub:", icon: "colors/dark_aqua.png", ping: 0}
      - !players
        playerSet: hub
        playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    1:
      - {text: "&7Rank: &3${viewer vault_primary_group}", icon: "colors/dark_gray.png", ping: 0}
	  - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
	  - {text: "&3Survival:", icon: "colors/dark_aqua.png", ping: 0}
      - !players
        playerSet: survival
        playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    2:
      - {text: "&cPing: ${viewer_colored_ping}ms", icon: "colors/dark_gray.png", ping: 0}
	  - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
      - {text: "&3KitPVP:", icon: "colors/dark_aqua.png", ping: 0}
      - !players
        playerSet: kitpvp
        playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
````

This is my coding, but when used in the server we're running, it doesn't work at all. It just displays the default tablist from a normal minecraft server. I've spent a few hours trying to search for errors in the configuration but I cannot figure out why is does not work.

It might be an obvious error, but as I said earlier I'm not an professional.

Could anyone help me with finding what's wrong with the code?
Thanks in advance!

-Gijs

**Comment by CodeCrafter47** [comment]
Have a look at the proxy log. When loading your config file it tells you something like this:
```
15:09:48 [INFO] [BungeeTabListPlus] Loading default.yml
15:09:48 [WARNING] [BungeeTabListPlus] Failed to load default.yml
while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 64, column 1:
        
    ^

    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
    at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226)
    at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
    at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:441)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:79)
    at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:75)
    at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:80)
    at codecrafter47.bungeetablistplus.BungeeTabListPlus.reloadTablists(BungeeTabListPlus.java:470)
    at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:94)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

What it tells you is basically, don't use tabs, use spaces instead.

**Comment by GijssiexD** [comment]
Thanks so much for the quick reply!
I didn't have access to the console itself so I set up a test bukkit server myself so I have access to the proxy myself.
Thanks again for your help!

**Comment by GijssiexD** [comment]
Okay, new problem.

I've removed all TABS I could find in the file, but now the server keeps loading the wrong file:

`03.03 16:58:36 [Server] WARNING [BungeeTabListPlus] Failed to load test2.yml03.03 16:58:36 [Server] INFO Cannot create property=showTo for JavaBean=codecrafter47.bungeetablistplus.config.FixedSizeConfig@2f46c3d803.03 16:58:36 [Server] INFO in 'reader', line 1, column 1:03.03 16:58:36 [Server] INFO showTo: "none"03.03 16:58:36 [Server] INFO ^03.03 16:58:36 [Server] INFO Can't construct a java object for scalar tag:yaml.org,2002:str; exception=null03.03 16:58:36 [Server] INFO in 'reader', line 1, column 9:03.03 16:58:36 [Server] INFO showTo: "none"03.03 16:58:36 [Server] INFO ^03.03 16:58:36 [Server] INFO in 'reader', line 1, column 9:03.03 16:58:36 [Server] INFO showTo: "none"03.03 16:58:36 [Server] INFO ^03.03 16:58:36 [Server] INFO at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:307)03.03 16:58:36 [Server] INFO at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)03.03 16:58:36 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)03.03 16:58:36 [Server] INFO at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:218)03.03 16:58:36 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)03.03 16:58:36 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)`

As you can see the tries to load test2.yml. We've removed all other files from the directory, didn't work.
We've reinstalled plugin, still didn't work.

If we use the default.yml that is used standard, no problems occur.

I don't know what causes this, please help.
Thanks in advance.

**Comment by GijssiexD** [comment]
UPDATE:

file loaded, next errors appeared, don't really know how to fix then:

`03.03 18:58:24 [Server] WARNING [BungeeTabListPlus] Failed to load default.yml03.03 18:58:24 
[Server] INFO while parsing a block mapping03.03 18:58:24 
[Server] INFO in 'reader', line 1, column 1:03.03 18:58:24 
[Server] INFO showTo: "all"03.03 18:58:24
[Server] INFO ^03.03 18:58:24 
[Server] INFO expected , but found BlockSequenceStart03.03 18:58:24 
[Server] INFO in 'reader', line 76, column 6:03.03 18:58:24 
[Server] INFO - !players03.03 18:58:24 [Server] INFO ^`

This is the current code:

```
showTo: "all"
priority: 24

showHeaderFooter: true

header:
- '&3Welcome &7${viewer name}'
- '&7W&3elcome &7${viewer name}'
- '&7We&3lcome &7${viewer name}'
- '&7Wel&3come &7${viewer name}'
- '&7Welc&3ome &7${viewer name}'
- '&7Welco&3me &7${viewer name}'
- '&7Welcom&3e &7${viewer name}'
- '&7Welcome &7${viewer name}'
- '&3W&7elcome &7${viewer name}'
- '&3We&7lcome &7${viewer name}'
- '&3Wel&7come &7${viewer name}'
- '&3Welc&7ome &7${viewer name}'
- '&3Welco&7me &7${viewer name}'
- '&3Welcom&7e &7${viewer name}'
- '&3Welcome &7${viewer name}'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &7SurviviaNetwork
  &3http://survivianetwork.buycraft.net
- |-
  &3SurviviaNetwork
  &7http://survivianetwork.buycraft.net

footerAnimationUpdateInterval: 0.5

customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: ' &3AFK'
    false: ''
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

playerSets:
  global:
    filter: "true"
  hub:
    filter: ${player server} == "hub"
  survival:
    filter: ${player server} == "survival"
  kitpvp:
    filter: ${player server} == "kitpvp"

type: FIXED_SIZE	
size: 60	

defaultIcon: colors/dark_gray.png
defaultPing: 1000


components:
- !table
  columns:
    0:
    - {text: "&7Server: &2${viewer server}", icon: "colors/dark_gray.png", ping: 0}
- {text: " ", icon: "colors/dark_gray.png", ping: 1000}
- {text: "&3Hub:", icon: "colors/dark_aqua.png", ping: 0}
     - !players
     playerSet: hub
    playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    1:
   - {text: "&7Rank: &3${viewer vault_primary_group}", icon: "colors/dark_gray.png", ping: 0}
  - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&3Survival:", icon: "colors/dark_aqua.png", ping: 0}
     - !players
       playerSet: survival
       playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    2:
     - {text: "&cPing: ${viewer_colored_ping}ms", icon: "colors/dark_gray.png", ping: 0}
     - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
     - {text: "&3KitPVP:", icon: "colors/dark_aqua.png", ping: 0}
     - !players
       playerSet: kitpvp
       playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
```

**Comment by CodeCrafter47** [comment]
It's not just about removing tabs. You still need to indent the lines properly.

This is the relevant part, indented properly:
```yaml
components:
- !table
  columns:
    0:
    - {text: "&7Server: &2${viewer server}", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3Hub:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: hub
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    1:
    - {text: "&7Rank: &3${viewer vault_primary_group}", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3Survival:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: survival
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
    2:
    - {text: "&cPing: ${viewer_colored_ping}ms", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3KitPVP:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: kitpvp
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
```

After this it still won't load because you need to configure the `morePlayersComponent` property for the `!players` component.

You can for example use 
```yaml
morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
```
which is used in the default config.

Here's the complete config with fixed indentation and added `morePlayersComponent` option:
```yaml
showTo: "all"
priority: 24

showHeaderFooter: true

header:
- '&3Welcome &7${viewer name}'
- '&7W&3elcome &7${viewer name}'
- '&7We&3lcome &7${viewer name}'
- '&7Wel&3come &7${viewer name}'
- '&7Welc&3ome &7${viewer name}'
- '&7Welco&3me &7${viewer name}'
- '&7Welcom&3e &7${viewer name}'
- '&7Welcome &7${viewer name}'
- '&3W&7elcome &7${viewer name}'
- '&3We&7lcome &7${viewer name}'
- '&3Wel&7come &7${viewer name}'
- '&3Welc&7ome &7${viewer name}'
- '&3Welco&7me &7${viewer name}'
- '&3Welcom&7e &7${viewer name}'
- '&3Welcome &7${viewer name}'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &7SurviviaNetwork
  &3http://survivianetwork.buycraft.net
- |-
  &3SurviviaNetwork
  &7http://survivianetwork.buycraft.net

footerAnimationUpdateInterval: 0.5

customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: ' &3AFK'
    false: ''
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"

playerSets:
  global:
    filter: "true"
  hub:
    filter: ${player server} == "hub"
  survival:
    filter: ${player server} == "survival"
  kitpvp:
    filter: ${player server} == "kitpvp"

type: FIXED_SIZE
size: 60

defaultIcon: colors/dark_gray.png
defaultPing: 1000

components:
- !table
  columns:
    0:
    - {text: "&7Server: &2${viewer server}", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3Hub:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: hub
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
      morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
    1:
    - {text: "&7Rank: &3${viewer vault_primary_group}", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3Survival:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: survival
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
      morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
    2:
    - {text: "&cPing: ${viewer_colored_ping}ms", icon: "colors/dark_gray.png", ping: 0}
    - {text: " ", icon: "colors/dark_gray.png", ping: 1000}
    - {text: "&3KitPVP:", icon: "colors/dark_aqua.png", ping: 0}
    - !players
      playerSet: kitpvp
      playerComponent: {text: "${player vault_prefix}${player name}${afk_tag}", icon: "${player skin}"}
      morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
```
