### ISSUE TITLE
Custom tablist

### ISSUE THREAD

**Issue by DanielAlves123** [CodeCrafter47/BungeeTabListPlus#214]
@CodeCrafter47 Hi, is it possible to create tablist such like that without creating Bukkit variables? Here's the link to the image: https://cl.ly/0X052T2Z0f32
On the left side would be some text, on top of the tablist would be a title "Players online": and the rest of the tablist would be online players.

**Comment by CodeCrafter47** [comment]
Of cause that is possible. You can configure it like that:
```yaml
showTo: 'true'
priority: 1

showHeaderFooter: false

playerSets:
  all_players:
    filter: all

type: FIXED_SIZE
size: 80 # The size of the tab list is increased to 80

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0: # leftmost column with text
    - {text: "&lInfo", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cServer:", icon: "default/server.png", ping: 0}
    - {text: "&6${viewer server}", icon: "default/server.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cRank:", icon: "default/rank.png", ping: 0}
    - {text: "&6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPing:", icon: "default/ping.png", ping: 0}
    - {text: "&6${viewer ping}ms", icon: "default/ping.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cPlayers:", icon: "default/players.png", ping: 0}
    - {text: "&6${playerset:all_players size}", icon: "default/players.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cBalance:", icon: "default/balance.png", ping: 0}
    - {text: "&6${viewer vault_balance}", icon: "default/balance.png", ping: 0}
    - {text: "", icon: "colors/gold.png", ping: 0}
    - {text: "&cTime:", icon: "default/clock.png", ping: 0}
    - {text: "&6${time HH:mm:ss}", icon: "default/clock.png", ping: 0}
    1-3: # Here the three columns at the right are configured
    - {text: "&b&lPlayers:", icon: "colors/aqua.png", ping: 0}
    - {text: ""}
    - {text: ""}
    - !players
      playerSet: all_players
      playerComponent: "${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
```
