### ISSUE TITLE
Disguising as another player breaks the tab list display order.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#239]
BungeeTabListPlus  2.8.1-SNAPSHOT dev 693

When you disguise as another player using a disguise plugin, the tab list breaks and places both you and the player you disguise as at the bottom of the list.

In my case, I used LibsDisguise typing ```/dis player <name>```.

![link](http://i.imgur.com/08gipLT.png)

Config.
```
playerSets:
  global:
    filter: "true"

type: FIXED_SIZE
size: 60 # 60 slots -> 3 columns, 20 rows

defaultIcon: colors/dark_gray.png
defaultPing: 1000

components:
- !players_by_server
  playerSet: global
  playerOrder: "vaultprefix,alphabetically"
  serverHeader:
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  serverSeparator:
  - {}
  - ""
  -
  includeEmptyServers: true
  playerComponent: "${player vault_prefix}${player display_name}${afk_tag}"
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
- !spacer {}
- {text: "&fServer: &b${viewer server}", icon: "default/server.png", ping: 0} # 20th row, 1st column
- {text: "&fPlayers: &b${playerset:global size}", icon: "default/players.png", ping: 0} # 20th row, 2nd column
- {text: "&fPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0} # 20th row, 3rd column
```
