### ISSUE TITLE
Is it possible to make someone's entire name grey when going AFK instead of appending an away status at the end?

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#242]

**Comment by CodeCrafter47** [comment]
Yes it is. Let's first have a look at the existing code to understand how it works. Here are the relevant parts of the `default.yml`:
```yaml
customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7|&oaway'
    false: ''

components:
- ...
- !players_by_server
  ...
  playerComponent: "${player vault_prefix}${player name}${afk_tag}"
```

First a custom placeholder called `afk_tag` is created that is set to `&7|&oaway` if the player is AFK. Then that placeholder is applied after the player's name.

To achieve what you want I suggest changing the `afk_tag` custom placeholder so that it is set to a gray color code if the player is AFK (e.g. `&7`) and applying it before the player's name:
```yaml
customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7' # <-- change the placeholder so it is replaced with just a color code
    false: ''

components:
- ...
- !players_by_server
  ...
  playerComponent: "${player vault_prefix}${afk_tag}${player name}" # <-- apply it before the player's name
```

**Comment by mibby** [comment]
I actually did try this change the other day before making the ticket, but unfortunately it did not change the player's name grey. It was as if the vault prefix took priority in the color coding. I even tried adding &r to the afk tag color.

**Comment by CodeCrafter47** [comment]
If you use a placeholder other than `${player name}` for the players name then that placeholder itself may already contain color codes which would cause it take precedence over previous color codes.

**Comment by mibby** [comment]
Ah, that could be it. I used display_name. I'll try normal ```name``` tomorrow and see if it updates correctly.

```
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7'
    false: ''
```
```
playerComponent: "${player vault_prefix}${afk_tag}${player display_name}"
```

**Comment by mibby** [comment]
Actually if I recall correctly, I had to use display_name so people who have custom in-game nicknames show up with that nickname on the tab. So I guess it isn't possible to colorize them if they are afk while keeping their nickname.

**Comment by mibby** [comment]
Unless you could add a way to override displayname formatting when a player's status is afk?

**Comment by CodeCrafter47** [comment]
You can use the custom placeholder mechanism to display the name using a different placeholder (i.e. `${player name}`)  when the player is afk.

**Comment by mibby** [comment]
How would I go about setting that up?

**Comment by CodeCrafter47** [comment]
```
customPlaceholders:
  afk_tag_and_name:
    !conditional
    condition: ${player essentials_afk}
    true: '&7${player name}'
    false: '${player display_name}'

playerComponent: "${player vault_prefix}${afk_tag_and_name}"
```
