### ISSUE TITLE
Change the icon depending on server status

### ISSUE THREAD

**Issue by Coolfeather2** [CodeCrafter47/BungeeTabListPlus#243]
in the server header, change the icon from green to red depending if the server is online or not

**Comment by CodeCrafter47** [comment]
That's possible:
```yaml
components:
- ...
- !players_by_server
  ...
  serverHeader:
  - !conditional
    condition: ${server online}
    true: {text: "&b&l>&3 ${server}(${server_player_count}):", icon: "colors/green.png", ping: 0}
    false: {text: "&b&l>&7 ${server}(Offline)", icon: "colors/red.png", ping: -1}
  ...
```
