### ISSUE TITLE
Is it possible to specify a custom name for a server in the serverHeader?

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#282]
```
  serverHeader:
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
```

I was wondering if it was possible to specify a custom name for a server in the server header. So you could rename a server something like Survival / Creative or provide another custom name for it.

**Comment by CodeCrafter47** [comment]
To create server aliases you can use the Custom Placeholder mechanism introduced in version 2.6.0 of BungeeTabListPlus.

General information on it can be found on the following wiki page, however it is not really well documented: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/CustomPlaceholders>.

Custom Placeholders can either be configured in the tab list configuration file or in the plugin's `config.yml` in which case they will be available for all tab list configuration files. Custom Placeholders are configured in the `customPlaceholders` section of the respective config file. If it doesn't exist just create it.

Here's the code for creating a server alias placeholder:
```yaml
customPlaceholders:
  # ...
  # add the following lines to your config to create the custom placeholder
  server_alias:
    !switch
    parameters: 1
    expression: "${%0}"
    replacements:
      # Begin user modifiable area
      "creative": "Creative"
      "survival": "Survival"
      "lobby0": "Lobby"
      "lobby1": "Lobby"
      # End user modifiable area
    defaultReplacement: "${%0}"
```

In the above code `server_alias` is the name of the Custom Placeholder. The actual aliases are configured in the lines between the _Begin/End user modifiable area_ comments. You can change these as required. You should not make changes to any other part of the code.

Now adding the Custom Placeholder code doesn't automatically make the server aliases show up. Instead it creates a set of new placeholders which can be used instead of the regular server name placeholders to display the alias instead of the real server name:

   * `${server_alias viewer server}` can be used instead of `${viewer server}` to display the alias of the server the player looking at the tab list is playing on.
   * `${server_alias player server}` can be used instead of `${player server}` to display the alias of a server a player displayed on the tab list is playing on.
   * `${server_alias server}` can be used instead of `${server}` in the serverHeader section of the !players_by_server component to display the alias of the server instead of the real server name there too.
   * `${server_alias server:lobby}` can be used to display the alias of a specific server, in this case lobby.

You can find lots of other examples on what Custom Placeholders can be used for on the wiki page about updating from a pre 2.6.0 config: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Updating>.
