### ISSUE TITLE
show only some prefix

### ISSUE THREAD

**Issue by mattymatty97** [CodeCrafter47/BungeeTabListPlus#297]
as the title is there a way to show prefixes of only some groups eg (admin and owners and not of players)?

**Comment by CodeCrafter47** [comment]
That is perfectly possible.

I assume you currently have something like the following in your config to display the prefix:
```yaml
  playerComponent: "${player vault_prefix}${player name}"
```
Now you can use a conditional component to distinguish two cases: the player being in the owner or admin group, or the player being in another group. In the latter case you'd remove the prefix placeholder:
```yaml
  playerComponent: !conditional
    condition: ${player vault_primary_group} == "admin" or ${player vault_primary_group} == "owner"
    true: "${player vault_prefix}${player name}"
    false: "${player name}"
```
