### ISSUE TITLE
Question: Complicated showTo and Condition

### ISSUE THREAD

**Issue by krusic22** [CodeCrafter47/BungeeTabListPlus#299]
I want to show another tablist for players that are on a server with more then 5 players...
Since you can't use custom condition nor use placeholders inside placeholders ${playerset:${player server} size}. Also ${server_player_count} doesn't work in showTo.
So am I missing something or is it currently not possible?

**Comment by CodeCrafter47** [comment]
You don't need to use placeholders inside placeholders for this as you can create a player set containing all players on the same server as the player looking at the tab list. Example:
```yaml
playerSets:
  currentserver:
    filter: |-
      ${player server} == ${viewer server}
```

However what you want to do still isn't possible as, for performance reasons, you cannot use player count placeholders in the `showTo` part of the configuration file.
