### ISSUE TITLE
Tablist glitches out randomly

### ISSUE THREAD

**Issue by TeamGameRevolution** [CodeCrafter47/BungeeTabListPlus#302]
We've been using BTLP for a while now and since our recent re-theme, the tablist just throws my config out of the window at random, showing 4 columns, with 20 rows each, where the last 2 columns are filled with Steve and Alex heads, a full connection and no name instead of 2 columns with 20 rows.

Here's our config:

```
showTo: "all"

priority: 1

type: FIXED_SIZE

showHeaderFooter: true

header:
- |-
  &3Welcome &b${viewer name}
  &bPlayers online: &f${playerset:noinvis size}

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &3Skyblock.xyz
  &fstore.skyblock.xyz
- |-
  &fSkyblock.xyz
  &3store.skyblock.xyz

footerAnimationUpdateInterval: 2.0

customPlaceholders:
  afk_color:
    !conditional
    condition: ${player essentials_afk}
    true: '&8&o'
    false: ''
  #viewer_colored_ping0:
   # !conditional
    #condition: "${viewer ping} < 50"
    #true: "&a${viewer ping}"
    #false: "&e${viewer ping}"
  #viewer_colored_ping:
   # !conditional
    #condition: "${viewer ping} < 150"
    #true: ${viewer_colored_ping0}
    #false: "&c${viewer ping}"

defaultIcon: colors/dark_gray.png
defaultPing: 1000
size: 40
playerSets:
  global:
    filter: "true"
  noinvis:
    filter: "true"
    hiddenPlayers: INVISIBLE
  lobby:
    filter: |-
      ${player server} == "sb"

components:
- !table
  columns:
    0-1:
      - {text: "&3&lSkyblock", icon: "colors/dark_aqua.png", ping: 0}
      - {text: "&3&lXYZ", icon: "colors/dark_aqua.png", ping: 0}
      - !players
        playerSet: lobby
        playerOrder: "AFKLast,vaultGroupInfo,alphabetically"
        fillSlotsVertical: true
        playerComponent: {text: "${player vault_prefix}${afk_color}${player name}${afk_tag}", icon: "${player skin}", ping: "${player ping}"}
        morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/dark_aqua.png", ping: 0}
```

Screenshots:

How it's supposed to look like:

![grafik](https://user-images.githubusercontent.com/1332113/34694467-78837926-f4c7-11e7-9af2-de043ca63b68.png)

How it looks like after it glitches:

![grafik](https://user-images.githubusercontent.com/1332113/34694494-975451cc-f4c7-11e7-8cd2-17730b370576.png)

Any ideas why this is happening?
