### ISSUE TITLE
Is grouping players by world possible?

### ISSUE THREAD

**Issue by roopekoo** [CodeCrafter47/BungeeTabListPlus#334]
Hi, I would like to know whether it is possible to put players on groups in the tab list same way as players in different servers do. If no one is in a certain world it would vanish from the list until someone joins that world. And If I don't want some world to be displayed, the player who is in that world will be placed eg on spawn world group.
If it isn't possible, can you tell if that feature would come in next releases at all?
My problem is that I have 2 servers. Other for minigames and other for everything else(Survival, spawn, creative). But naming doesn't make any sense; Player is on survival but tab list says Spawn and those who are in minigames are alone in the right column of the tab list while others take up the other side.

If grouping to worlds isn't possible another way is to join the minigames players to the main spawn server group.
Images:
1: This is what I have
![1 original](https://user-images.githubusercontent.com/6078487/37800961-6de9d7d6-2e2d-11e8-9a6d-3b8af3dcaedb.png)

2: This is what I would like(Have the players grouped by their current worlds)
![2 world groups](https://user-images.githubusercontent.com/6078487/37800968-7456ad9c-2e2d-11e8-96e9-613cc5ddd81e.png)

3: This is what would be the second option(Joining Minigames to spawn)
![3 joined minigames](https://user-images.githubusercontent.com/6078487/37800978-78cbaa76-2e2d-11e8-9077-03020f029634.png)

**Comment by CodeCrafter47** [comment]
You can do the 3rd variant by using the `!players` component to display all players in the 2nd and 3rd column:

```
showTo: all
priority: 1

showHeaderFooter: false

playerSets:
  all_players:
    filter: all

type: FIXED_SIZE
size: 80

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0:
    - ...
    1-2:
    - !players
      playerSet: all_players
      playerComponent: "${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    3:
    - ...
```

-------------------

To do the second variant more effort is required. You need to create a _player set_ for each world that you want to display and then use a combination of the `!conditional` and `!players` components to display the players in the 2nd and 3rd column. This means basically you'll be doing what the `!players_by_server` component does, but you're doing it manually:

 ```
showTo: all
priority: 1

showHeaderFooter: false

playerSets:
  all_players:
    filter: all
  group1:
    filter: ${player server} == "spawn" and ${player world} == "spawn"
  group2:
    filter: ${player server} == "spawn" and ${player world} == "survival"
  group3:
    filter: ${player server} == "spawn" and ${player world} == "creative"
  group4:
    filter: ${player server} == "minigames"

type: FIXED_SIZE
size: 80

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0:
    - ...
    1-2:
    - !conditional
      condition: '${playerset:group1 size} > 0'
      false: []
      true:
      - {text: 'Spawn', icon: 'colors/aqua.png'}
      - {text: '${playerset:group1 size} players', icon: 'colors/aqua.png'}
      - !players
        playerSet: group1
        playerComponent: "${player name}"
        morePlayersComponent: '... and ${other_count} others'
      -
      -
    - !table {}
    - !conditional
      condition: '${playerset:group2 size} > 0'
      false: []
      true:
      - {text: 'Survival', icon: 'colors/aqua.png'}
      - {text: '${playerset:group2 size} players', icon: 'colors/aqua.png'}
      - !players
        playerSet: group2
        playerComponent: "${player name}"
        morePlayersComponent: '... and ${other_count} others'
      -
      -
    - !table {}
    - !conditional
      condition: '${playerset:group3 size} > 0'
      false: []
      true:
      - {text: 'Creative', icon: 'colors/aqua.png'}
      - {text: '${playerset:group3 size} players', icon: 'colors/aqua.png'}
      - !players
        playerSet: group3
        playerComponent: "${player name}"
        morePlayersComponent: '... and ${other_count} others'
      -
      -
    - !table {}
    - !conditional
      condition: '${playerset:group4 size} > 0'
      false: []
      true:
      - {text: 'Minigames', icon: 'colors/aqua.png'}
      - {text: '${playerset:group4 size} players', icon: 'colors/aqua.png'}
      - !players
        playerSet: group4
        playerComponent: "${player name}"
        morePlayersComponent: '... and ${other_count} others'
    3:
    - ...
```

I didn't test any of this but I think it should work. Short explanation how it works:
```
    - !conditional
      condition: '${playerset:group1 size} > 0'
```
This line tests whether there are any players in the player set. The player set `group1` is the one with the players on the spawn world on the spawn server.
```
      false: []
```
This line makes sure nothing is displayed if there are no players in the player set.
```
      true:
      - {text: 'Spawn', icon: 'colors/aqua.png'}
      - {text: '${playerset:group1 size} players', icon: 'colors/aqua.png'}
```
After the `true:` follow the things that are displayed if there are players in that player set. First two things to display are the server name and the number of players.
```
      - !players
        playerSet: group1
        playerComponent: "${player name}"
        morePlayersComponent: '... and ${other_count} others'
```
The `!players` component takes care of displaying the players
```
      -
      -
```
Two empty slots create some distance to the next 'server'. This isn't needed for the last one. 
```
    - !table {}
```
This line doesn't display anything, it just makes sure that whatever is displayed next goes in the left column, i.e. this line may or may not add an additional empty slot as required.
