### ISSUE TITLE
Per-Server tablist not working... AGAIN

### ISSUE THREAD

**Issue by meandpiggy** [CodeCrafter47/BungeeTabListPlus#357]
Hi... I followed the instructions in the wiki to create per-server tablists... But I got 2 players online at once and it didn't work. This is what all the different tablists look like:

```
showTo: '${viewer server} == "the server name"'
priority: 5

playerSets:
  all_players:
    filter: "true"
    hiddenPlayers: "INVISIBLE"

showHeaderFooter: true
header:
- '&cPixel&6Me'
headerAnimationUpdateInterval: 1.0
footer:
- '&cEnjoy your stay on the server!'
footerAnimationUpdateInterval: 1.0

type: DYNAMIC_SIZE

playerSet: all_players

playerOrder: "LuckPermsGroupInfo"

playerComponent: "${player luckperms_prefix}${player name}"
```

Please help! Thanks!

EDIT: Oh yeah, the default one looks like this:
```
showTo: "all"
priority: 0

playerSets:
  all_players:
    filter: "true"
    hiddenPlayers: "INVISIBLE"

```

Will that affect anything?

**Comment by CodeCrafter47** [comment]
You can learn how to use markdown to format code at <https://guides.github.com/features/mastering-markdown/>.

In you server-specific tab list configuration you have
```yaml
showTo: '${viewer server} == "the server name"'
priority: 5
```

That is fine. The tab list is displayed only to players on that server and it preferred over the default one because it has a higher priority.

The reason why you think it's not working is probably because both tab lists do exactly the same. They display all players and the same header and footer.

If you want to only display the players on the same server as the player looking at the tab list you can use the following config options:
```yaml
playerSets:
  same_server:
    filter: ${player server} == ${viewer server}
    hiddenPlayers: INVISIBLE

playerSet: same_server
```
Note that you do not need separate configuration file for your servers to do that.

Another thing you should be aware of is that `hiddenPlayers: INVISIBLE` does not work very well when using a dynamic size tab list. I recommend to either use `VISIBLE_TO_ADMINS` or `VISIBLE`.
