### ISSUE TITLE
Need help with playerSet

### ISSUE THREAD

**Issue by weronicamc** [CodeCrafter47/BungeeTabListPlus#369]
Hello, I want a tablist, where players can see only players on actually server. I little bit dont understand, how I can set it. Thank you for help :)

**Comment by CodeCrafter47** [comment]
Sorry for the late answer, I somehow missed this issue.

To display only the players on the same server as the player looking at the tab list you have to create a player set containing only those players:
```yaml
# locate the playerSets section
playerSets:
  # add the following two lines
  same_server:
    filter: ${player server} == ${viewer server}
```

Then you can

- use `${playerset:same_server size}` to display the number of players
- replace `playerSet: all_players` with `playerSet: same_server` to change which players are displayed on the tab list.

Here's a complete config displaying only players on the same server as the player looking at the tab list:
```yaml
showTo: all
priority: 10

showHeaderFooter: true
header:
- '&cWelcome &f${viewer name}'
headerAnimationUpdateInterval: 0.5
footer:
- '&f&oPowered by BungeeTabListPlus'
footerAnimationUpdateInterval: 0.5

playerSets:
  global:
    filter: all
    hiddenPlayers: VISIBLE_TO_ADMINS
  same_server:
    filter: ${player server} == ${viewer server}
    hiddenPlayers: VISIBLE_TO_ADMINS

type: FIXED_SIZE
size: 60
defaultIcon: colors/dark_gray.png
defaultPing: 1000

components:
- {text: "&cServer: &6${viewer server}", icon: "default/server.png", ping: 0}
- {text: "&cRank: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
- {text: "&cPing: ${viewer ping}ms", icon: "default/ping.png", ping: 0}
# An empty row
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
# Here are the players
- !players
  playerSet: same_server
  playerOrder: "adminFirst,alphabetically"
  playerComponent: "${player vault_prefix}${player name}"
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
  minSize: 48
  maxSize: 48
# Another empty row
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "", icon: "colors/dark_gray.png", ping: 1000}
- {text: "&cTime: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
- {text: "&cPlayers: &6${playerset:global size}", icon: "default/players.png", ping: 0}
- {text: "&cBalance: &6${viewer vault_balance 1.2}$", icon: "default/balance.png", ping: 0}
```
