### ISSUE TITLE
minSizePerServer not working

### ISSUE THREAD

**Issue by Direcka** [CodeCrafter47/BungeeTabListPlus#385]
Hello,

I need little bit help with minSizePerServer, which is not working for me. I dont know if I am doing something wrong or its just bug. I've done some Layout before and I want you addapt it to be more automatic for new server etc. You cand find YML code below. Actual status looks like this

![Actual status](https://user-images.githubusercontent.com/14356883/44542616-a5a0ea80-a70d-11e8-814f-5e9929b728e9.png)

And I wanted just set minimum size per each server in all except first row to be balanced 

![wanted](https://user-images.githubusercontent.com/14356883/44542771-16e09d80-a70e-11e8-9126-9ceb9be5ebc9.png)

Here is my code

```yaml
showTo: 'all'
priority: 1
showHeaderFooter: true

header:
- '&5&lModRealms §fNetwork - &cServer: &6${viewer server}'

headerAnimationUpdateInterval: 0.2

footer:
- |-
  §5Need any Help? §dJoin our Discord!
  Use /discord command to get link!
- |-
  §5Need any Help? §dJoin our Discord!
  §5Use /discord command to get link!
footerAnimationUpdateInterval: 0.5

playerSets:
  all_players:
    filter: all
  Active:
    filter: ${player server} == ${viewer server}
  Rest:
    filter: ${player server} != ${viewer server}

  

type: FIXED_SIZE
size: 80
defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0:
    - {text: "§d${viewer server} §f(${playerset:Active size}):", icon: "colors/dark_purple.png", ping: 0}
    - !players
        playerSet: Active
        playerComponent: "${player name}"
        morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    1-3:
    - !players_by_server   
      fillSlotsVertical: true  
      playerSet: Rest
      serverHeader:
        - {text: "§d${server}&f&o (${server_player_count}):", icon: "colors/dark_purple.png", ping: 0}
      serverSeparator:
        - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      
      showServers: ALL
      playerComponent: "${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
      minSizePerServer: 10
 ```
