### ISSUE TITLE
Help with colums

### ISSUE THREAD

**Issue by ronc617** [CodeCrafter47/BungeeTabListPlus#400]
Hoping you can help me with columns
I am trying to have staff listed on the top right column and have it for 7 spaces
then under that im trying to have the rest of the players start to fill in across columns 0-2
and fill in everything vertically. when i change it from column 0 to 0-2 everything goes out of whack 
and i really cant figure out what i am doing wrong
any help in the correct direction would be great

https://pastebin.com/Vvd4x8DU

**Comment by CodeCrafter47** [comment]
You can use the container component:
```yaml
    0-3:
    - !container
      fillSlotsVertical: true
      components:
        - {text: "&4&lStaff", icon: "colors/red.png", ping: 0}
        - !players
          ...
        - {text: "&bPlayers", icon: "colors/green.png", ping: 0}
        - !players
          ...
```
