### ISSUE TITLE
Misformatted TabList on 1.7 clients

### ISSUE THREAD

**Issue by TheFlash787** [CodeCrafter47/BungeeTabListPlus#402]
Hey! So we're using this configuration to create a tablist on our servers.
```yml
showTo: 'all'
priority: 1
showHeaderFooter: true

header:
- |-
  §5&lModRealms §fNetwork
  §cServer: §6${viewer server} &f- &cPlayers: §6${playerset:all_players size} §f- &cPing: ${viewer_colored_ping}ms &cTPS: ${viewer_colored_tps} &f- &cBalance: &6£0.00${viewer vault_balance 1.2}

headerAnimationUpdateInterval: 0.2

footer:
- |-
  &cServer Time: &f${time H:mm:ss}
  §5Need any Help? §dJoin our Discord!
  Use /discord command to get link!
- |-
  &cServer Time: &f${time H:mm:ss}
  §5Need any Help? §dJoin our Discord!
  §5Use /discord command to get link!
footerAnimationUpdateInterval: 0.5

customPlaceholders:
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"

  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&a${viewer ping}"

  viewer_colored_tps0:
    !conditional
    condition: "${viewer server tps} < 10"
    true: "&c${viewer server tps}"
    false: "&e${viewer server tps}"

  viewer_colored_tps:
    !conditional
    condition: "${viewer server tps} < 15"
    true: ${viewer_colored_tps0}
    false: "&a${viewer server tps}"

playerSets:
  all_players:
    filter: all
  Active:
    filter: ${player server} == ${viewer server}
  Rest:
    filter: ${player server} != ${viewer server}

type: FIXED_SIZE
size: 80
defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0:
    - {text: "§d${viewer server} §f(${playerset:Active size}):", icon: "colors/dark_purple.png", ping: 0}
    - !players
        playerSet: Active
        playerComponent: "${player name}"
        morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    1-3:
    - !players_by_server   
      fillSlotsVertical: true  
      playerSet: Rest
      serverHeader:
        - {text: "§d${server}&f&o (${server_player_count}):", icon: "colors/dark_purple.png", ping: 0}
      serverSeparator:
        - {text: "", icon: "colors/dark_gray.png", ping: 1000}
      
      showServers: ALL
      playerComponent: "${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
      minSizePerServer: 9
```

**__However, this is the result on a 1.7.10 client:__**
![image](https://user-images.githubusercontent.com/25883284/51088922-9de5ef00-175d-11e9-9a11-c8baa50c02a3.png)

**__Expected Result (on a 1.10 - 1.12 client):__**
![image](https://user-images.githubusercontent.com/25883284/51088979-26648f80-175e-11e9-8f90-ca3c40b14362.png)

However, you will notice that **Hub** has a second box which should've been replaced by another server that we have.

We had an issue regarding a tablist previously, too (which was fixed by an updated version later on) https://github.com/CodeCrafter47/BungeeTabListPlus/issues/385
