### ISSUE TITLE
Animated custom placeholder

### ISSUE THREAD

**Issue by RadYio** [CodeCrafter47/BungeeTabListPlus#406]
Thank's a lot for your plugin.

I just want to put an animated text Reboot, reboot.., reboot... etc.. next to the name of my server in the bungeetablistplus, but i get some error when i have to reload.

Error code : https://pastebin.com/C7ViaQEn
I try with this config: `etatlobby:
    !conditional
    condition: "${server:Lobby online}"
    true: ":"
    false: " &cReboot"
  etatevent:
    !conditional
    condition: "${server:Event online}"
    true: ":"
    false:
    !animated
    interval: 0.5
    components: 
    - {text: " &cReboot."}
    - {text: " &cReboot.."}
    - {text: " &cReboot..."}
    - {text: " &cReboot.."}`

The etatlobby: it's ok, but not the etatevent..

**Comment by RadYio** [comment]
config pastebin: https://pastebin.com/B75qCL6X
Maybe more easy to watch with the good syntax.

**Comment by CodeCrafter47** [comment]
There are basically two errors here:

1. The indentation is wrong. You need to add additional spaces to the `!animated` section:
```yaml
  etatevent:
    !conditional
    condition: "${server:Event online}"
    true: ":"
    false:
      !animated
      interval: 0.5
      components: 
      - {text: " &cReboot."}
      - {text: " &cReboot.."}
      - {text: " &cReboot..."}
      - {text: " &cReboot.."}
```

2. `!animated` cannot be used in a custom placeholder. See <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Animations> for an example of correct usage.
