### ISSUE TITLE
Incorrect layout

### ISSUE THREAD

**Issue by alvarlagerlof** [CodeCrafter47/BungeeTabListPlus#427]
![image](https://user-images.githubusercontent.com/14835120/57965592-91a9b280-7946-11e9-9b78-de318312dbdf.png)

```
showTo: "true"
priority: 1

showHeaderFooter: false

playerSets:
  all_players:
    filter: "all"

type: FIXED_SIZE

size: 60

defaultIcon: colors/gray.png
defaultPing: 1000

components:
- !players_by_server
  playerSet: all_players
  serverHeader:
  - {text: '&2&l>&2 ${server} (${server_player_count}):', icon: 'colors/dark_green.png'}
  serverSeparator:
  -
  -
  -
  -
  showServers: NON_EMPTY
  playerComponent: "${player name}"
  morePlayersComponent: '... and ${other_count} others'
```
