### ISSUE TITLE
A way to prioritize the current server's tab list

### ISSUE THREAD

**Issue by kmecpp** [CodeCrafter47/BungeeTabListPlus#430]
Currently I have my tab list to group players by servers which there are about 5 of. This is very helpful if there are not that many people as everyone can see everyone on the server but during peak times this system becomes very cluttered.

Correct me if I'm wrong but I don't think there is currently anyway to use this system but "prioritize" the current server a player is playing on. So for example if the tab list becomes so crowded that it will begin showing "and X more.." for the current server. Instead of doing that, there should be a config option to have the tab list switch to only show players for the current server.

Alternatively and probably more simply you could just add a config option to switch to per server tablists at a specific player count.

**Comment by CodeCrafter47** [comment]
I think you can do something like this:
```yaml
playerSets:
  all_players:
    filter: all
  same_server:
    filter: ${player server} == ${viewer server}

components:
- ...
- !conditional
  condition: ${playerset:all_players size} < 20
  true:
  - !players_by_server
    playerSet: all_players
    playerComponent: "${player name}"
    morePlayersComponent: '... and ${other_count} others'
  false:
  - !players
    playerSet: same_server
    playerComponent: "${player name}"
    morePlayersComponent: '... and ${other_count} others'
```
I didn't test the above, but I think it is correct.

**Comment by kmecpp** [comment]
I get 

`Caused by: java.lang.NullPointerException: serverHeader is null` at the line `  - !players_by_server` when i use that

**Comment by CodeCrafter47** [comment]
```yaml
 true:
  - !players_by_server
    playerSet: all_players
    playerComponent: "${player name}"
    morePlayersComponent: '... and ${other_count} others'
    serverHeader:
    - '&b&l>&3 ${server}(${server_player_count}):'
```
