### ISSUE TITLE
every server online player does mix with this config

### ISSUE THREAD

**Issue by ham1255** [CodeCrafter47/BungeeTabListPlus#437]
```
- !players
      playerSet: all_players
      playerComponent: "${player ultraperms_prefix} ${player name}"
      morePlayersComponent: '... and ${other_count} others'
```

**Comment by ham1255** [comment]
all i want every server has it own online players

**Comment by CodeCrafter47** [comment]
You're still telling the plugin to display all players via the `playerSet: all_players` line.

To change that you need to add a new player set in the `playerSet` section of the config. In this case I called it `same_server`.
```yaml
playerSets:
  all_players:
    filter: all
  same_server:
    filter: ${player server} == ${viewer server}
```

Then you change the `playerSet`  option to use the new player set: `playerSet: same_server`.

If you want to find out more about how to configure the plugin I recommend you have a look at the [wiki](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki), everything is explained there.
