### ISSUE TITLE
Round !compute ?

### ISSUE THREAD

**Issue by matahombres** [CodeCrafter47/BungeeTabListPlus#456]
```  health_percentage:
   !compute
    (${viewer health} / ${viewer max_health}) * 100
```

How i can round?

**Comment by CodeCrafter47** [comment]
Rounding is not possible currently. I think this needs to change, though. So I will look into adding this functionality to the plugin with the next update.

**Comment by CodeCrafter47** [comment]
The latest dev-build adds number formatting options for custom placeholders. It also changes the default format to 2 decimal places.

Let's take the example of the health percentage placeholder:
```yaml
customPlaceholders:
  health_percentage:
    !compute
    (${viewer health} / ${viewer max_health}) * 100
```

You can use `${health_percentage 1.0}` for not decimal places, `${health_percentage 1.1}` for one decimal place and ${health_percentage 1.2}` gives the default of two decimal places.
