### ISSUE TITLE
playerSet 

### ISSUE THREAD

**Issue by NuNeTomas** [CodeCrafter47/BungeeTabListPlus#475]
http://prntscr.com/q7z7d0 in the picture you can see that i have multiple servers and have my main and alt connected on different servers but i cant figure out how to make so it would show when im connected to lobby and when to survival. here is my config https://pastebin.com/LCy8BWiB

**Comment by CodeCrafter47** [comment]
You can do that by using the `!table` component.

Replace
```yaml
  - !players
    playerSet: Lobby
    playerOrder: "alphabetically"
    playerComponent:
      - {text: "&8 [&b☆&8]&f ${player tab_name} ${afk_tag}"}
    morePlayersComponent: {text: "&b +${other_count} &7players"}
    fillSlotsVertical: true
  - !players
    playerSet: Survival
    playerOrder: "alphabetically"
    playerComponent:
      - {text: "&8 [&b☆&8]&f ${player tab_name} ${afk_tag}"}
    morePlayersComponent: {text: "&b +${other_count} &7players"}
    fillSlotsVertical: true
```
with
```yaml
  - !table
    colums:
      0:
      - !players
        playerSet: Lobby
        playerOrder: "alphabetically"
        playerComponent:
          - {text: "&8 [&b☆&8]&f ${player tab_name} ${afk_tag}"}
        morePlayersComponent: {text: "&b +${other_count} &7players"}
        fillSlotsVertical: true
      1:
      - !players
        playerSet: Survival
        playerOrder: "alphabetically"
        playerComponent:
          - {text: "&8 [&b☆&8]&f ${player tab_name} ${afk_tag}"}
        morePlayersComponent: {text: "&b +${other_count} &7players"}
        fillSlotsVertical: true
```

You can find some examples using the `!table` component on the following wiki page: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-8---Fixed-Size-Tablist---Table>.

As a side note: I do not think you need the `fillSlotsVertical`.
