### ISSUE TITLE
Issue regarding BTLP in hub

### ISSUE THREAD

**Issue by SilentRoses** [CodeCrafter47/BungeeTabListPlus#477]
I've been attemting a few new things regarding BTLP in my hub server. However i've ran into a few small hiccups. Hiccup one. As you can see the ranks are listing alphabetically not depending on the users luckperms rank. Hiccup two, i have a staff list via hub to show all online staff across the network however no staff ranks are showing up. I feel it's likely my configuration skills that's caused this however all help is welcome. Last issue was spacing between the servers. as you can see the servers and the players can be seen via tab however i don't want the tab to expand as players join i just want it to display a few of the highesr ranking players on the server and the others If you'd like further info feel free to add me on discord **SilentRoses#1234** (I will post the config there as it's fully custom and don't really wanna share it publicly. Thanks!) Thanks ~ Phoebe
![image](https://user-images.githubusercontent.com/45537340/71102639-bc940780-21b0-11ea-834f-226a6ea16230.png)

![image](https://user-images.githubusercontent.com/45537340/71102506-8a82a580-21b0-11ea-9a55-4b61016a1ba0.png)

**Comment by CodeCrafter47** [comment]
Player order with luckperms is a bit tricky. First you need to make sure every group has a weight assigned to it. BungeeTabListPlus will use those weights to sort the players.
Then you need to set the `playerOrder` property to `LuckPermsGroupInfo`. If that sorts the players the wrong way round you can use `LuckPermsGroupInfoReversed` instead. If you have not installed LuckPerms on BungeeCord or did not setup permission syncing via the MySQL database, you should use `vaultGroupInfo` instead.
Last you can append the `alphabetically` option to sort players with the same rank alphabetically. In total your `playerOrder` option should look like this:
```yaml
- !players
  playerSet: hub
  playerOrder: "LuckPermsGroupInfo,alphabetically"
  # ...
```
Note that you have to set this option for each `!players` component.

Regarding spacing between servers, you can use the `minSize` and `maxSize` options of the `!players` component to prevent it from dynamically adjusting its size. The following example fixes the size to 5 players:
```yaml
    - !players
      playerSet: hub
      playerComponent: "${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
      minSize: 5
      maxSize: 5
```
