### ISSUE TITLE
Custom Prefix Question

### ISSUE THREAD

**Issue by MrAmos123** [CodeCrafter47/BungeeTabListPlus#480]
How can I format the tab list so depending on what server they're connected to it'll display the rank associated with that server?

See below LuckPerms output for my network. Default group according to Bungee is 'default', yet on SBerry/Anarchy the ranks are different. I'd like the TAB list to reflect the rank associated with the server they're on.

An example would be tab list would look like this: (Also, it's not sorting correctly either...)
SBerry: https://i.imgur.com/DfQmgeL.png
Anarchy: https://i.imgur.com/siIlFlU.png
```
Anarchy: [M] Ayymoss
SBerry: [A] Ayymoss
```

I'm using this example from your Wiki; https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples#global-tab-list-dynamic-size 

My configuration: https://pastebin.com/raw/nmF1RVY6

```
> lpb user ayymoss info
[12:47:03 INFO]: [LP] > User Info: ayymoss
[12:47:03 INFO]: [LP] - UUID: 9ac1880f-26ac-4469-9e58-c3fe04d6a54c (type: mojang)
[12:47:03 INFO]: [LP] - Status: Online
[12:47:03 INFO]: [LP] - Primary Group: default
[12:47:03 INFO]: [LP] - Parent Groups:
[12:47:03 INFO]: [LP] -    > sb_admin (server=sberry)
[12:47:03 INFO]: [LP] -    > fr_moderator (server=anarchy)
[12:47:03 INFO]: [LP] -    > default
[12:47:03 INFO]: [LP] - Contextual Data:
[12:47:03 INFO]: [LP] -    Has contextual data: true
[12:47:03 INFO]: [LP] -    Applicable contexts: (server=bungee) (world=sberry)
[12:47:03 INFO]: [LP] -    Prefix: None
[12:47:03 INFO]: [LP] -    Suffix: None
[12:47:03 INFO]: [LP] -    Meta: (weight=5)
```

**Comment by CodeCrafter47** [comment]
You could try using `vault_primary_group` instead of `luckperms_primary_group`. That way the primary group will be queried on the spigot server, where it hopefully will pick up the correct group.

If that works out you can probably fix the player order the same way by using `VaultGroupInfo`.

**Comment by MrAmos123** [comment]
When I use `vault_primary_group` it just seems to remove all the information. Though I do not have Vault installed on the Bungee server (if that matters) the Bridge is installed on the Spigot servers, however. Any further ideas about how I could make this happen? I appreciate the fast response btw. :)

**Comment by CodeCrafter47** [comment]
You can use the `vault_primary_group` placeholder to directly display the group, so you can see what it is. If it does not display anything there is probably something wrong with the bridge setup. In that case you can use the `/btlp status` command to check whether BungeeTabListPlus thinks the bridge is installed.
If `vault_primary_group` just displays `default` you probably need to change something with your LuckPerms setup.

**Comment by MrAmos123** [comment]
Yeah, it sees `default` because it doesn't use primary group without matching server.

Is it possible to implement some feature to check the server-specific group? 

```
> btlp status
[16:31:32 INFO]: You are running BungeeTabListPlus version 2.8.12
[16:31:32 INFO]: Looking for an update...
[16:31:32 INFO]: You are already running the latest version.
[16:31:32 INFO]: Bridge plugin status:
[16:31:32 INFO]: Installed on: Hub, SBerry, Anarchy
[16:31:32 INFO]: Thank you for using BungeeTabListPlus.
```

**Comment by CodeCrafter47** [comment]
I think `vault_primary_group` should give the server specific primary group, but I could be wrong. Would `/lp user ayymoss info` give a different primary group than `/lpb user ayymoss info`?

**Comment by MrAmos123** [comment]
Yeah, so they return different primary groups.

See this: https://i.imgur.com/S7IOQzY.png

Using `vault_primary_group` does work... I'm mistaken. https://i.imgur.com/3JNXXG4.png However, something doesn't work here... To get this to show I did `    true: ' ${player vault_primary_group} &7'`

With the below cfg, the TAB list looks like this; https://i.imgur.com/R9qvUOy.png any idea?

```yml
customPlaceholders:
  custom_prefix:
    !switch
    parameters: 1
    expression: ${%0 vault_primary_group}
    replacements:
      "SB Admin": "&c&lA &8»&r"
      "SB Community Manager": "&5&lC &8»&r"
      "SB Helper": "&3&lH &8»&r"
      "Fr Founder": "&4&lF &8»&r"
      "Fr Administrator": "&c&lA &8»&r"
      "Fr Developer": "&9&lD &8»&r"
      "Fr Moderator": "&3&lM &8»&r"
      "Fr Donator 100": "&e&lD &8»&r"
      "Fr Donator 20": "&2&lD &8»&r"
      "Fr Donator": "&6&lD &8»&r"
      "Default": "&7&lP &8»&r"
    defaultReplacement: "&r"
  other_server_prefix: # makes players on other servers gray
    !conditional
    condition: '${viewer server} == ${player server}'
    true: ' ${custom_prefix viewer} &7'
    false: ' &8✦ » '

playerSets:
  global:
    filter: "true"
    hiddenPlayers: "VISIBLE" # Hidden players show up on the tab list, avoids gliches

playerSet: global

playerOrder: "playerServerFirst,VaultGroupInfo,serverAlphabetically,alphabetically"

#playerComponent: "${other_server_prefix}${player name}"
playerComponent: "${other_server_prefix}${player name}"
```
