### ISSUE TITLE
Tablist messed up.

### ISSUE THREAD

**Issue by MstrTaffy** [CodeCrafter47/BungeeTabListPlus#483]
BTLP - 2.8.12/2.8.13 SNAPSHOT
BUNGEE - Waterfall - 309
SURVIVAL - Paper 1.15.1 - 33
LOBBY - Paper 1.13.2 - 636 

Tablist works fine on the Lobby but in the Survival server is looks messed up. 

Lobby
![Lobby](https://user-images.githubusercontent.com/30232425/72065242-ec5aa900-3331-11ea-896c-5fdd7ec2b98c.png)

Survival
![Survival](https://user-images.githubusercontent.com/30232425/72065257-f54b7a80-3331-11ea-8ea1-4567acbe3615.png)

BTLP Config
```
# This is the configuration file of BungeeTabListPlus
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki for additional information

# if enabled the plugin checks for new versions automatically.
# Use /BTLP to see whether a new version is available
# this does NOT automatically install an update
checkForUpdates: true

# this notifies admins (everyone with the permission `bungeetablistplus.admin`) if an update is available
notifyAdminsIfUpdateAvailable: true

# Interval (in seconds) at which all servers of your network get pinged to check whether they are online
# If you intend to use the {onlineState:SERVER} variable set this to 2 or any value you like
# setting this to -1 disables this feature
pingDelay: 2

# those fakeplayers will randomly appear on the tablist. If you don't put any names there then no fakeplayers will appear
fakePlayers: []

# Servers which you wish to show their own tabList (The one provided by bukkit)
# Players on these servers don't see the custom tab list provided by BungeeTabListPlus
excludeServers: []

# Players on these servers are hidden from the tab list.
# Doesn't necessarily hide the server from the tab list.
hiddenServers: []

# players which are permanently hidden from the tab list
# you can either put your username or your uuid (with dashes) here
# don't use this. you have absolutely no reason to hide from anyone. on your own server.
hiddenPlayers: []

# Time zone to use for the {time} variable
# Can be full name like "America/Los_Angeles"
# or custom id like "GMT+8"
time-zone: Australia/Hobart

# Custom placeholders
customPlaceholders: {}

```
BTLP Tablist
```
# This is the default configuration file of BungeeTabListPlus.
#
# Since the configuration of the plugin is quite complex you
# might want to have a look at the wiki from time to time.
# 
# Wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
#  Placeholders: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders
#  Examples: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples
#

# It is possible to have multiple tab list configuration files.
# BungeeTabListPlus will parse all .yml files it finds in the tabLists directory.
# Which tab list a player sees depends on the showTo and priority options.

# All player see this tab list
showTo: "all"

# Examples of alternative options for showTo:
# showTo: ' ${viewer server} == "Factions" '
# showTo: ' ${viewer server} == "Factions" or ${viewer server} == "Survival" '
# showTo: ' ${viewer vault_primary_group} == "Admin" '

# If after evaluating the showTo option of all tab list configs multiple tab lists
# are visible to a player, he will bw shown the one with the highest priority:
priority: 0

# Tab list header and footer:
showHeaderFooter: true

header:
- '&6Welcome &7to &d&n&lTaffyNet&f ${viewer name}! &7You are on ver: ${viewer client_version}!'


headerAnimationUpdateInterval: 0.5

footer:
- '&6&lJoin our Discord - &r&e&ndiscord.taffynet.net'


footerAnimationUpdateInterval: 0.5

# Custom placeholders are a powerful mechanism to add more dynamic content
# to the tab list.
customPlaceholders:
  # Defines the ${afk_tag} placeholder which is used to add "|away"
  # to the players name if he is afk.
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7|&oaway'
    false: ''
  # Defines the ${viewer_colored_ping0} placeholder which displays the ping in green
  # if it is below 50ms, otherwise in yellow.
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  # Defines ${the viewer_colored_ping} placeholder which displays the ping in red
  # if it is above 150ms, otherwise it is replaced with the ${viewer_colored_ping0}
  # placeholder ( < 50 -> green, > 50 -> yellow).
  # That results in the following color scheme:
  # 0 - 49   -> green
  # 50 - 149 -> yellow
  # 150+     -> red
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"
   
  serveronline:
    !conditional
    condition: ${server online}
    true: "&b${server}"
    false: "&c${server}"
  
# Player sets are required to display players and player counts on the tab list.
# To display a player count use ${playerset:<name> size}, example: ${playerset:global size}.
playerSets:
  # The global player set contains all players
  global:
    filter: "true"
# # Some more examples. Be careful to get the number of spaces right when using them.
# # Player set containing all players on a specific server:
# survival:
#   filter: |-
#     ${player server} == "survival"
# # Player set containing all players on the same server as the player viewing the tab list:
# currentserver:
#   filter: |-
#     ${player server} == ${viewer server}
# # Player set containing all players on a specific server and world:
# survival_nether:
#   filter: |-
#     ${player server} == "survival"
#     and ${player world} == "world_nether"
# # Player set containing all admins:
# admins:
#   filter: |-
#     ${player vault_primary_group} == "admin"
#     or ${player vault_primary_group} == "owner"

# We want the tab list to have a fixed size of 60 slots.
# If you want a dynamic size you need to set type to DYNAMIC_SIZE
# and you don't need any of the options below it. Have a look at
# the example in the wiki to see which options you need instead:
# https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples#global-tab-list-dynamic-size
type: FIXED_SIZE
size: 60 # 60 slots ->3 columns, 20 rows

# The defaultIcon and defaultPing will be used for all slots for which no other value is
# explicitely set.
defaultIcon: colors/dark_gray.png
defaultPing: 1000

# Here the content of the tab list is configured:
components:
# Three info slots at the top
- {text: " &aServer: &6${viewer server}", icon: "default/server_green.png", ping: 0} # 1st row, 1st column
- {text: " &aPlayers: &6${playerset:global size}", icon: "default/players_green.png", ping: 0} # 1st row, 2nd column
# Show ping in different colors depending on how good/ bad it is
- {text: " &aPing: ${viewer_colored_ping}ms", icon: "default/ping_green.png", ping: 0} # 1st row, 3rd column
# A row of empty slots below
- {text: "", icon: "colors/dark_gray.png", ping: 1000} # 2nd row, 1st column
- {text: ""} # 2nd row, 2nd column; Since icon and ping are the default they don't need to be specified explicitely.
- {} # 2nd row, 3rd column; Since the text is empty it doesn't need to be specified either
# The players by server component adds players to the tab list grouped by server
- !players_by_server
  # The global player set is configured above
  playerSet: global
  playerOrder: "LuckPermsGroupInfoReversed,alphabetically"
  serverOrder: custom
  customServerOrder: [Lobby, Vanilla, Heroes, Rev]
  # The server header is shown for each server above the players on that server.
  # We use it to display the server name and the player count.
  serverHeader:
  - {text: " ${serveronline}&f&o (${server_player_count})", icon: "default/server_aqua.png", ping: 0}
  # The server separator is shown between two consecutive servers. 
  # Here it use used to separate the servers with an empty row of slots, showing two more variants to display an empty slot.
  serverSeparator:
  - {}
  - ""
  -
  # Whether empty servers should show up too
  includeEmptyServers: true
  # Format of the player slot. Add prefixes as you like
  playerComponent: "${player luckperms_prefix}${player name}"
  # If there isn't enough space for all players the morePlayersComponent is displayed. We use to to display the number of players which couldn't be displayed on the tab list.
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
# A spacer creates as many empty slots as possible.
- !spacer {}
# Because the spacer has eaten up all the remaining free slots, the nine slots below are guaranteed to be at the bottom of the tab list.
# Let's start with another empty row
- "" # 18th row, 1st column
- "" # 18th row, 2nd column
- "" # 18th row, 3rd column
# Then some nice animations at the bottom
- !animated # 19th row, 1st column
  interval: 0.5
  components:
  - {text: "&a&2=&a==============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=&2=&a=============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==&2=&a============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===&2=&a===========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a====&2=&a==========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=====&2=&a=========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a======&2=&a========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=======&2=&a=======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a========&2=&a======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=========&2=&a=====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==========&2=&a====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===========&2=&a===", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a============&2=&a==", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=============&2=&a=", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==============&2=&a", icon: "colors/dark_green.png", ping: 0}
- !animated # 19th row, 2nd column
  interval: 0.5
  components:
  - {text: "&a&2=&a==============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=&2=&a=============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==&2=&a============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===&2=&a===========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a====&2=&a==========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=====&2=&a=========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a======&2=&a========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=======&2=&a=======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a========&2=&a======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=========&2=&a=====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==========&2=&a====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===========&2=&a===", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a============&2=&a==", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=============&2=&a=", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==============&2=&a", icon: "colors/dark_green.png", ping: 0}
- !animated # 19th row, 3rd column
  interval: 0.5
  components:
  - {text: "&a&2=&a==============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=&2=&a=============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==&2=&a============", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===&2=&a===========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a====&2=&a==========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=====&2=&a=========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a======&2=&a========", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=======&2=&a=======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a========&2=&a======", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=========&2=&a=====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==========&2=&a====", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a===========&2=&a===", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a============&2=&a==", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a=============&2=&a=", icon: "colors/dark_green.png", ping: 0}
  - {text: "&a==============&2=&a", icon: "colors/dark_green.png", ping: 0}
```
