### ISSUE TITLE
"showServers" query

### ISSUE THREAD

**Issue by HHServers** [CodeCrafter47/BungeeTabListPlus#501]
Hey, how would I use showServers to exclude certain servers from the list. for example if an Events server is only online at the weekend i don't want it to clutter the tab list during the week

**Comment by CodeCrafter47** [comment]
The only way you can use the `showServers` option for this is by setting it to `ONLINE` or `NON_EMPTY`, so that it will not show servers which are offline, or have no players respectively. This will affect all servers though.

Alternatively there is a `hiddenServers` option you can use. It allows you to remove specific servers from the list. It looks like this:
```yaml
!players_by_server
playerSet: global
showServers: ALL
hiddenServers: [hub, private]
```
