### ISSUE TITLE
Create custom placeholder without !conditional or !compute

### ISSUE THREAD

**Issue by khang-hoang** [CodeCrafter47/BungeeTabListPlus#515]
How can i create a custom placeholder without specifying a !conditional or !compute?
I've try 
```yaml
customPlaceholders:
  hub_online:
    - ${hub_online_color}${playerset:hub size}/100
```
But it not working.
