### ISSUE TITLE
Header changes if no chat is sent

### ISSUE THREAD

**Issue by psrcek** [CodeCrafter47/BungeeTabListPlus#543]
I've found this weird issue where if no chat is received for roughly 10 seconds the header text is changed. the header lines become non-strikethrough and any animated placeholders I put there stop working. If you chat again it repairs itself. I have no idea how this plugin is related to chat in any way.

Also it only happens in the header and not in the footer??? WTF!

![image](https://user-images.githubusercontent.com/13370323/77239285-4ea91300-6bd9-11ea-89a4-6b292fbc388b.png)

After waiting 10s: 
![image](https://user-images.githubusercontent.com/13370323/77239256-c0cd2800-6bd8-11ea-98fd-08869877f71b.png)

And then after chatting: 
![image](https://user-images.githubusercontent.com/13370323/77239266-ed813f80-6bd8-11ea-8278-4d5f037f7b18.png)

Related tablist config options;
```yaml
showHeaderFooter: true
header: |-
    &8&m----------------[&7 Welcome ${fancy_player viewer}&7 to [REDACTED] &8&m]----------------&8
    &cIP: &6[REDACTED]
    &6                                                                                                                                                                                                         &6
    &6                                                                                                                                                                                                         &6
footer:
  - |-
    ${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}
    &6                                                                                                                                                                                                         &6
    &6Server is currently being built!
    &7Be patient...
  - |-
    ${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}${animated_line}
    &6                                                                                                                                                                                                         &6
    &6Server is currently being built!
    &7Report any bugs you find!
footerAnimationUpdateInterval: 4

customPlaceholders:
  animated_line:
    !animated
    interval: 0.08
    elements:
    - "&6&m&c&m &6&m                        "
    - "&6&m &c&m &6&m                       "
    - "&6&m  &c&m &6&m                      "
    - "&6&m   &c&m &6&m                     "
    - "&6&m    &c&m &6&m                    "
    - "&6&m     &c&m &6&m                   "
    - "&6&m      &c&m &6&m                  "
    - "&6&m       &c&m &6&m                 "
    - "&6&m        &c&m &6&m                "
    - "&6&m         &c&m &6&m               "
    - "&6&m          &c&m &6&m              "
    - "&6&m           &c&m &6&m             "
    - "&6&m            &c&m &6&m            "
    - "&6&m             &c&m &6&m           "
    - "&6&m              &c&m &6&m          "
    - "&6&m               &c&m &6&m         "
    - "&6&m                &c&m &6&m        "
    - "&6&m                 &c&m &6&m       "
    - "&6&m                  &c&m &6&m      "
    - "&6&m                   &c&m &6&m     "
    - "&6&m                    &c&m &6&m    "
    - "&6&m                     &c&m &6&m   "
    - "&6&m                      &c&m &6&m  "
    - "&6&m                       &c&m &6&m "
    - "&6&m                        &c&m &6&m"
  fancy_player:
    !conditional
    parameters: 1
    condition: "true"
    true: "${vanish_tag %0}${afk_tag %0}&7&f[${%0 luckpermsbungee_prefix}&f] &7${%0 name}&7${%0 luckpermsbungee_suffix}"
    false: "&4&lWTF HOW"
  afk_tag:
    !conditional
    parameters: 1
    condition: ${%0 essentials_afk}
    #true: "&7• "
    true: "&7[AFK] "
    false: ""
  vanish_tag:
    !conditional
    parameters: 1
    condition: ${%0 is_hidden}
    true: "&7&l[V] "
    false: ""
```
