### ISSUE TITLE
Custom Placeholders in Icon

### ISSUE THREAD

**Issue by Sander0542** [CodeCrafter47/BungeeTabListPlus#559]
## Info

I am trying to set the icon of a server based on the online placeholder of a server, but it is giving a purple and black image in the icon.

This custom placeholder works when I try to add it as an text to the server. (Screenshot below)

## Config

```yml
components:
- !players_by_server
  playerSet: all_players
  serverOrder: online,alphabetically
  serverHeader:
  - { text: '${server_display_name server}', icon: "${server_online}" }
  - '&7Players: &f${server_player_count}'
  - '&7TPS: &f${server tps}'
  - '${server_online}'
  serverSeparator:
  -
  -
  -
  showServers: ALL
  playerComponent: "${player display_name}${afk_tag}"

customPlaceholders:
  server_online:
    !conditional
    condition: ${server online}
    true: 'colors/green.png'
    false: 'colors/red.png'
```

## Result

![image](https://user-images.githubusercontent.com/11409610/78985725-c4920180-7b29-11ea-9e39-3a2f02726741.png)

### Online

![image](https://user-images.githubusercontent.com/11409610/78985812-028f2580-7b2a-11ea-9e8d-6af090d3a987.png)

### Offline

![image](https://user-images.githubusercontent.com/11409610/78985834-0fac1480-7b2a-11ea-9937-950a90fa1746.png)

### Online

![image](https://user-images.githubusercontent.com/11409610/78985962-6ade0700-7b2a-11ea-9430-231bfd63b495.png)

### Offline

![image](https://user-images.githubusercontent.com/11409610/78985999-834e2180-7b2a-11ea-9a53-42b6848c3754.png)
