### ISSUE TITLE
playerSets

### ISSUE THREAD

**Issue by wallxq** [CodeCrafter47/BungeeTabListPlus#562]
I cant set playerSets. 
```
showTo: "all"
priority: 0

# Hidden players show up on the tab list, avoids glitches
hiddenPlayers: VISIBLE

playerSets:
  all_players: all

# A simple header and footer
showHeaderFooter: true
header: |-
  &f&lJesteś na: ${viewer server}
  &f&lWszyscy gracze: ${playerset:Wszyscy size}
  &f&lJanuszowo: ${playerset:Januszowo size}
  &f&lCH1: ${playerset:CH1 size}
  &f&lCH2: ${playerset:CH2 size}
headerAnimationUpdateInterval: 1.0
footer: |-
  &f&lGodzina: &f${time H:mm}
  &f&lPing: &f${viewer ping}
  &f&lBank: &6&o${viewer vault_balance} &o&eYang
footerAnimationUpdateInterval: 1.0

# We want a dynamic size tab list
type: DYNAMIC_SIZE

# Below are the options specific to the dynamic size tab list

# Here you can configure which players to display by specifying a player set.
# For this example we are using the `all_players` player set created above.
playerSet:
  Wszyscy: all
  Januszowo: ${player server} == "Januszowo"
  CH1: ${player server} == "CH1"
  CH2: ${player server} == "CH2"
# Here the order of the players can be configured.
playerOrder: "vault_primary_group_weight desc, name asc"

# This option controls the format of the players names.
playerComponent: "${player vault_prefix}${player name}"
```
Console:

> while constructing a mapping
> in 'reader', line 1, column 1:
> showTo: "all"
> ^
> found duplicate key playerSets
> in 'reader', line 32, column 1:
> playerSets:
> ^

**Comment by CodeCrafter47** [comment]
You have
```yaml
playerSets:
  all_players: all
```
and
```yaml
playerSet:
  Wszyscy: all
  Januszowo: ${player server} == "Januszowo"
  CH1: ${player server} == "CH1"
  CH2: ${player server} == "CH2"
```
I'm assuming when the error message was created the second one also said `playerSets` - cause that's what the error message says - way have the `playerSets` option twice.

You should have the `playerSets` option once - this is where you create the player sets.

Then you should also have the `playerSet` option once. This is where you tell the plugin which players to display by giving the name of a player set. It should look like this:
```yaml
playerSet: all_players
```
