### ISSUE TITLE
BungeePerms group server display(name) Placeholder

### ISSUE THREAD

**Issue by KNNI** [CodeCrafter47/BungeeTabListPlus#563]
[bad EN]
The following placeholders exist:
${viewer bungeeperms_display} & ${player bungeeperms_display}
However, these placeholders only pick up the General Display from the respective group.
If you specify a display name for a server, it will not be placed. No matter if the "Main Displayname" is set or not.
Therefore I suggest a placeholder for the server display name.
It could look like this:
${viewer bungeeperms_display_server} & ${player bungeeperms_display_server}
Under the German part you will find examples of the current situation.

[DE]
Folgende Platzhalter existieren:
${viewer bungeeperms_display} & ${player bungeeperms_display}
Nun hab ich das Problem, dass dieser Platzhalter nur auf den Gruppen Display Namen zugreift jedoch nicht auf den Server basierten Display Namen. Dabei ist es egal, ob der Gruppen Display Namen gesetzt ist oder nicht.
Deswegen schlage ich einen Platzhalter vor, der sich auf die Server gesetzten Displaynamen bezieht.
Könnte eventuell so aussehen:
${viewer bungeeperms_display_server} & ${player bungeeperms_display_server}
Vielleicht versteht man mich hiermit besser, was ich meine:

current situation examples
BungeePerms YAML
```
  Besitzer:
    inheritances: []
    permissions:
    - '*'
    ladder: default
    default: false
    display: Besitzer
    prefix: '&4'
    servers:
      survival:
        inheritances: []
        permissions: []
        display: König
        prefix: '&6'
```
BungeeTablistPlus
```
- {text: "&7Gruppe: ${viewer bungeeperms_prefix}${viewer bungeeperms_display}", icon: "colors/gray.png", alignment: CENTER, ping: 0}
```
Ingame:
![image](https://user-images.githubusercontent.com/18620563/79392610-ecdb8f00-7f73-11ea-848a-a7ee532c8e65.png)

The "König" is completely ignored. The placeholder prefix is currently formed from both prefixes (&4&6).
Currently there is no possibility to display the display name of the server.
And while you're at it, you might want to add extra placeholders for prefix and suffix of the server. You can also set these extra.

Das "König" wird komplett ignoriert. Der Platzhalter Prefix wird derzeit aus beiden prefixen gebildet (&4&6).
Derzeit hat man keine Möglichkeit den Displaynamen des Servers anzeigen zu lassen.
Und wenn man gerade dabei ist, kann man eventuell extra Platzhalter für Prefix und Suffix der Server. Diese kann man ebenfalls extra setzten.
