### ISSUE TITLE
Placeholders do not work correctly

### ISSUE THREAD

**Issue by deeprobin** [CodeCrafter47/BungeeTabListPlus#572]
Error
```
WARNING: Unknown placeholder ${%0 vault_primary_group}
in 'reader', line 32, column 17:
        expression: ${%0 vault_primary_group}
                    ^
in use of placeholder ${custom_prefix}
in 'reader', line 18, column 18:
    playerComponent: "${custom_prefix}${player name}$ ...
```

default.yml
```yml
showTo: all
priority: 0

# Hidden players show up on the tab list, avoids glitches
hiddenPlayers: VISIBLE

playerSets:
  all_players: all

showHeaderFooter: true
header: " \n &6&lChaosOlymp.de  \n&aOnline &8» &f${playerset:all_players size}  &8┃  &ePing &8» &f${viewer ping}\n "
footer: " \n&7Server &8» &e${viewer server}\n "

type: DYNAMIC_SIZE

playerSet: all_players
playerOrder: "vault_primary_group_weight desc, name asc"
playerComponent: "${custom_prefix player}${player name}${afk_tag}"

customPlaceholders:
  # Defines the ${afk_tag} placeholder which is used to add "|away"
  # to the players name if he is afk.
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: " &8[&eAFK&8]"
    false: ""
  custom_prefix:
    !switch
    parameters: 1
    expression: ${%0 vault_primary_group}
    replacements:
      "admin": "&4Admin &8┃ &7"
      "moderator": "&cMod &8┃ &7"
      "supporter": "&9Sup &8┃ &7"
      "helfer": "&2Helfer &8┃ &7"
      "jrdeveloper": "&bDev &8┃ &7"
      "developer": "&bDev &8┃ &7"
      "jrbuilder": "&eBuild &8┃ &7"
      "builder": "&eBuild &8┃ &7"
      "default": "&7"
      "expert": "&7"
      "pro": "&7"
      "prime": "&7"
      "legend": "&7"
    defaultReplacement: "&7"
```
