### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by AodX** [CodeCrafter47/BungeeTabListPlus#605]
i would like to know how to fix that error, i tried my best to edit the config and gone to the Wiki but sadly i couldn't fix it,

can anyone here help me fix it ?

here is my config 

```
showTo: "all"
priority: 0

showHeaderFooter: true
header:
- '&6&l⟢  &eWelcome &b${viewer name} &eto &6&lAvolore  &6&l⟣'
- '&6&l⟢ &eWelcome &b${viewer name} &eto &6&lAvolore &6&l⟣'
headerAnimationUpdateInterval: 0.5
footer:
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &6&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&6&lA&e&lvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lA&6&lvo&e&llore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvo&6&ll&e&lore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvol&6&lo&e&lre&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolo&6&lr&e&le&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lC&6&lom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
- "&6»» &b&lPlayers&8&l: &e${playerset:global size} &a⦿ &8&l⎜ &6&lIP&8&l: &e&lMc&7.&e&lAvolore&7.&e&lCom &6««"
footerAnimationUpdateInterval: 0.1

customPlaceholders: 
  colored_ping0:
    !conditional
    condition: ${%0 ping} < 99
    true: "&a${%0 ping}"
    false: "&e${%0 ping}"
  colored_ping:
    !conditional
    parameters: 1
    condition: ${%0 ping} < 499
    true: ${colored_ping0 %0}
    false: "&c${%0 ping}"
  colored_ping1:
    !conditional
    parameters: 2
    condition: ${%0 ping} > 499
    true: "&4${colored_ping0 %0}"
    false: "${%0 ping}"

playerSets:
  global:
    filter: true
  local_server:
    filter: ${player server} == ${viewer server}
  Lobby:
    filter: ${player server} == "Lobby"
  Prison:
    filter: ${player server} == "Prison"
  FFA:
    filter: ${player server} == "FFA"
  # ...

type: FIXED_SIZE

size: 80

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0-2:
    - {text: "&c&l&n${viewer server}:", icon: "colors/red.png", ping: 0}
    - !players
      playerSet: local_server
      playerComponent: "${viewer_colored_ping} &f${player mysqlnicks_nickname}"

# With suffix
#     playerComponent: "&7${player ping} &f${player mysqlnicks_nickname} &7${player vault_suffix}"

      morePlayersComponent: "... and ${other_count} others"
    3:
    - {text: "&6&lServers", icon: "colors/gold.png", ping: 0, alignment: CENTER}
    - "&f&lLobby&8&l:"
    - "&6&lPlayers&8&l: &e${playerset:Lobby size}"
    - ""
    - "&9&lPrison&8&l:"
    - "&6&lPlayers&8&l: &e${playerset:Prison size}"
    - ""
    - "&d&lFFA&8&l:"
    - "&6&lPlayers&8&l: &e${playerset:FFA size}"
```

and here is the error i get

```
00:47:52 [WARNING] [BungeeTabListPlus] There have been 1 warnings while loading plugins/BungeeTabListPlus/tabLists/default.yml
WARNING: Unknown placeholder ${viewer_colored_ping}
 in 'reader', line 75, column 24:
          playerComponent: "${viewer_colored_ping} &f${play ... 
                           ^
```
