### ISSUE TITLE
Placeholder and vps ovh which connects to home paper servers with open ports.

### ISSUE THREAD

**Issue by wallxq** [CodeCrafter47/BungeeTabListPlus#611]
I have a problem with the status of my servers. At the moment when I moved bungeecord to vps, placeholders to server status are not working properly. For example, I have 3 servers. It shows 1 lobby under TAB, it is online. The next two I have turned off and TAB shows offline, i.e. correctly. After turning on the servers, it changes to ONLINE, which is correct. The problem starts when I shut down the servers. Status does not change from ONLINE to OFFLINE. Plugin reload doesn't help. Only re-enabling bungecrod.

`server_state:
    !conditional
    parameters: 1
    condition: ${server:%Test online}
    true: "&aOnline"
    false: "&cOffline"`

**Comment by PrinceBunBun981** [comment]
The only problem I see is with your condition, as it should be `${server:%0 online}` not `${server:%Test online}`. And the placeholder to actually get if the server is online or offline would be `${server_state (server)}` (e.g. `${server_state lobby}`)

**Comment by wallxq** [comment]
0 online? its not true. "test" its name of server than 0 can't be name of server. Than `${server_state (server)}` not working. My problem was "%". Just i remove % behind name of server and this work.

**Comment by Andre601** [comment]
To clear things up as it was probably confused a bit:
When using the `${server:<name> online}` option does `<name>` need to be the server name you want to use.

The `%0` is usually used when creating custom placeholders that may require a specific parameter (e.g. the Server name) to be provided.

Example:
```yaml
customPlaceholders:
  serverState:
    !conditional
    parameters: 1 # Requires 1 parameter (The server name)
    condition: ${server:%0 online} # %0 would be the first parameter provided in the placeholder (${serverState <name>})
    true: '&aOnline'
    false: '&cOffline'

# Imagine all the other stuff here for the tab list

components
- {text: "&7Hub ${serverState hub}"}
- # all the other slots...
```
The above example would be a custom placeholder where I provide the name of the server to return the online state from, which is either `&aOnline` or `&cOffline`

I hope this clears things up. If not then take a look at this wiki page:
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Custom-Placeholders#parameters
