### ISSUE TITLE
Disable spaces (prefix & AFK)

### ISSUE THREAD

**Issue by matyasvane** [CodeCrafter47/BungeeTabListPlus#654]
Hey,
I have created a functional tablist for the server, but if I don't have a prefix or AFK status, I see a space in the player.

How i can remove spaces?

![image](https://user-images.githubusercontent.com/75536352/133799081-de4179b6-f0ff-4426-a1eb-7dbb5c17c670.png)

```
showTo: ${viewer server} == "Survival"
priority: 0

hiddenPlayers: VISIBLE

playerSets:
  all_players: all
  auth: ${player server} == "auth"
  survival: ${player server} == "survival"
  same_server: ${player server} == ${viewer server}
  group2:
    filter: ${player server} == "Survival"

showHeaderFooter: true
header: |-
  &7
  &3&lSERVER
  &7(&3${playerset:all_players size}&7/&350&7)
  &7
footer: |-
  &f
  &fServer: &3${viewer server}    &7:    &fOnline: &3${playerset:same_server size}&7/&350

type: DYNAMIC_SIZE

playerSet: group2
playerOrder: "luckpermsbungee_primary_group_weight desc, name asc"
playerComponent: "${afk_tag player} ${player luckpermsbungee_prefix} ${player name}"
customPlaceholders:
  afk_tag:
    !conditional
    parameters: 1
    condition: ${%0 essentials_afk}
    true: '&cAFK&7 &4|&r'
    false: ''
```

And yes, this problem is only if player not have any prefix (luckperms or afk). If "MAJITEL" not have AFK, he have some problem, but only with space AFK

![image](https://user-images.githubusercontent.com/75536352/133800088-8a245122-8c87-4c80-badc-6e73f2340bc7.png)
